// V19.5 — tests mélangés + vraies activités de compréhension/expression
(function(){
'use strict';
const cache=new Map();let player=null;

// Complète les 8 leçons de base jusqu'à 30 leçons.
const extra=[
['La famille',[['Mamm','mère'],['Papp','père'],['Kand','enfant'],['Famill','famille']]],
['Les jours',[['Méindeg','lundi'],['Dënschdeg','mardi'],['Mëttwoch','mercredi'],['Donneschdeg','jeudi'],['Freideg','vendredi']]],
['Les moments de la journée',[['Moien','matin'],['Mëtteg','midi'],['Owend','soir'],['Nuecht','nuit']]],
['L’heure',[['Auer','heure'],['hallef','demie'],['Véierel','quart'],['Minutt','minute']]],
['La maison',[['Haus','maison'],['Kichen','cuisine'],['Schlofzëmmer','chambre'],['Buedzëmmer','salle de bain']]],
['Manger et boire',[['Waasser','eau'],['Brout','pain'],['Mëllech','lait'],['Kaffi','café'],['iessen','manger']]],
['Faire les courses',[['Buttek','magasin'],['Präis','prix'],['bezuelen','payer'],['kafen','acheter']]],
['Se déplacer',[['Bus','bus'],['Zuch','train'],['Gare','gare'],['Auto','voiture'],['fueren','aller en véhicule']]],
['En ville',[['Strooss','rue'],['Plaz','place'],['riets','à droite'],['lénks','à gauche']]],
['Le travail',[['Aarbecht','travail'],['schaffen','travailler'],['Kolleg','collègue'],['Büro','bureau']]],
['Les loisirs',[['Sport','sport'],['Musek','musique'],['liesen','lire'],['spadséieren','se promener']]],
['La météo',[['Wieder','météo'],['Sonn','soleil'],['Reen','pluie'],['kal','froid'],['waarm','chaud']]],
['Le corps et la santé',[['Kapp','tête'],['Hand','main'],['Dokter','médecin'],['Péng','douleur'],['krank','malade']]],
['Les vêtements',[['Jackett','veste'],['Schong','chaussures'],['Box','pantalon'],['Hemd','chemise']]],
['Au restaurant',[['Menu','menu'],['Iessen','repas'],['Gedrénks','boisson'],['Rechnung','addition']]],
['Parler de ses goûts',[['gär','aimer / volontiers'],['léiwer','préférer'],['gutt','bon / bien'],['net gär','ne pas aimer']]],
['Le passé récent',[['gëschter','hier'],['war','était'],['hat','avait'],['gemaach','fait']]],
['Le futur et les projets',[['muer','demain'],['wäert','va / sera'],['plangen','prévoir'],['goen','aller']]],
['Décrire une personne',[['grouss','grand'],['kleng','petit'],['jonk','jeune'],['al','âgé']]],
['Décrire une image',[['Bild','image'],['gesinn','voir'],['virun','devant'],['hannert','derrière'],['nieft','à côté de']]],
['Donner son avis',[['ech mengen','je pense'],['fir mech','pour moi'],['well','parce que'],['awer','mais']]],
['Préparation Sproochentest',[['verstoen','comprendre'],['widderhuelen','répéter'],['méi lues','plus lentement'],['Ech weess et net','Je ne sais pas']]]
];
if(lessons.length<30)extra.forEach(x=>lessons.push({title:x[0],sub:x[1].length+' éléments à maîtriser',words:x[1],quiz:[]}));

const oralPrompts={
0:'Salue quelqu’un, puis prends congé.',1:'Dis « je », « tu », « nous » à voix haute sans regarder.',2:'Fais une mini-phrase avec « je suis ».',3:'Présente-toi : nom, origine et lieu d’habitation.',4:'Dis ton âge ou invente un âge simple.',5:'Pose une question avec « où » ou « comment ».',6:'Joue seul un mini-dialogue : bonjour, comment ça va, réponse, au revoir.',7:'Dis en une phrase ce que tu comprends des mots « actualités », « aujourd’hui », « Luxembourg ».',
8:'Présente rapidement ta famille.',9:'Dis quel jour nous sommes puis cite un autre jour.',10:'Dis si nous sommes le matin, midi, soir ou nuit.',11:'Donne une heure simple à voix haute.',12:'Décris deux pièces de ton logement.',13:'Dis ce que tu bois et ce que tu manges.',14:'Imagine que tu achètes quelque chose : dis magasin, prix, acheter ou payer.',15:'Explique en une phrase comment tu te déplaces.',16:'Donne une direction simple : à gauche ou à droite.',17:'Dis où tu travailles ou invente une réponse.',18:'Parle d’un loisir que tu aimes.',19:'Décris la météo en deux mots.',20:'Explique simplement où tu as mal.',21:'Cite deux vêtements que tu portes.',22:'Imagine une commande au restaurant.',23:'Dis ce que tu aimes puis ce que tu préfères.',24:'Dis une chose faite hier.',25:'Dis un projet pour demain.',26:'Décris une personne en deux adjectifs.',27:'Décris mentalement une image avec devant / derrière / à côté.',28:'Donne ton avis et ajoute une raison avec « parce que ».',29:'Entraîne-toi à demander de répéter ou de parler plus lentement.'
};

const style=document.createElement('style');style.textContent=`
.overviewGrid{display:grid;grid-template-columns:repeat(2,1fr);gap:10px;margin:12px 0}.metric{padding:14px;border:1px solid var(--line);border-radius:16px;background:#fff}.metric strong{display:block;font-size:24px}.metric span{font-size:12px;color:var(--muted)}
.skillCard{padding:15px;border:1px solid var(--line);border-radius:16px;margin:10px 0;background:#fff}.skillCard h4{margin:0 0 5px}.skillCard p{margin:0;color:var(--muted);font-size:13px;line-height:1.4}.phase{margin-top:12px;padding:10px 12px;border-radius:12px;background:#f5f8fc;font-size:13px}
.selfQ{font-size:23px;font-weight:850;margin:18px 0}.reveal{padding:16px;border-radius:14px;background:#eef5fb;margin:12px 0;font-size:22px;font-weight:850}.judge{display:grid;grid-template-columns:1fr 1fr;gap:9px;margin-top:12px}.judge button{padding:14px;border-radius:13px;font-weight:800}.yes{background:var(--green2);color:var(--green)}.no{background:var(--red2);color:var(--red)}
.exerciseType{display:inline-block;padding:6px 9px;border-radius:999px;background:var(--blue2);color:var(--blue);font-size:12px;font-weight:850;margin-bottom:10px}.exerciseBox{padding:18px;border:1px solid var(--line);border-radius:18px;background:#fff;margin-bottom:12px}.exerciseBox h3{margin:2px 0 8px}.exerciseBox p{line-height:1.45}.lessonPlan{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:12px 0}.lessonPlan div{padding:10px;border-radius:12px;background:#f5f8fc;text-align:center;font-size:12px}.lessonPlan b{display:block;font-size:18px;margin-bottom:3px}
`;document.head.appendChild(style);

function clean(s){return String(s||'').replace(/[.…?!,:;]/g,'').trim()}
function norm(s){return String(s||'').normalize('NFKD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/^file:/,'').replace(/\.(ogg|oga|mp3|wav|webm)$/,'').replace(/[^a-z0-9]/g,'')}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
async function audioUrl(word){if(cache.has(word))return cache.get(word);const target=norm(word);for(const q of [`intitle:${word} incategory:"Luxembourgish pronunciation"`,`"${word}" Luxembourgish pronunciation`]){try{const u='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=30&prop=imageinfo&iiprop=url|extmetadata&format=json&origin=*&gsrsearch='+encodeURIComponent(q);const j=await fetch(u,{cache:'no-store'}).then(r=>r.json());let best=null,score=-1;for(const p of Object.values(j.query?.pages||{})){const ii=p.imageinfo?.[0];if(!ii)continue;const t=norm(p.title);let s=t.includes(target)?40:0;if(t===target||t==='lb'+target)s+=100;if(s>score){score=s;best=ii.url}}if(best&&score>=40){cache.set(word,best);return best}}catch(e){}}cache.set(word,null);return null}
async function handleAudio(btn){const row=btn.closest('.word'),word=clean(row?.querySelector('.lux')?.textContent),st=row?.querySelector('.audioStatus');btn.textContent='⏳ Recherche…';btn.disabled=true;if(st)st.textContent='Recherche de la prononciation humaine…';if(!word||word.includes(' ')){btn.disabled=false;btn.textContent='🔊 Écouter';if(st)st.textContent='Audio disponible uniquement pour les mots isolés.';return}const url=await audioUrl(word);btn.disabled=false;btn.textContent='🔊 Écouter';if(!url){if(st)st.textContent='Pas encore d’audio humain vérifié.';return}try{player?.pause();player=new Audio(url);await player.play();if(st)st.textContent='Prononciation humaine'}catch(e){if(st)st.textContent='Lecture impossible sur cet appareil.'}}
document.addEventListener('click',e=>{const b=e.target.closest?.('.audioBtn');if(!b)return;e.preventDefault();e.stopImmediatePropagation();handleAudio(b)},true);

const oldRenderHome=renderHome;
window.renderHome=function(){oldRenderHome();const totalWords=lessons.reduce((n,l)=>n+l.words.length,0),doneWords=lessons.filter((l,i)=>state.done.includes(i)).reduce((n,l)=>n+l.words.length,0);const hero=document.querySelector('#home .hero');let box=document.getElementById('overviewBox');if(!box){box=document.createElement('div');box.id='overviewBox';hero.insertAdjacentElement('afterend',box)}const done=state.done.length,pct=Math.round(done/lessons.length*100);box.innerHTML=`<div class="card"><div class="eyebrow">Vue d'ensemble</div><h3 style="margin:6px 0">Programme complet</h3><div class="overviewGrid"><div class="metric"><strong>${done}/${lessons.length}</strong><span>leçons terminées</span></div><div class="metric"><strong>${pct}%</strong><span>progression globale</span></div><div class="metric"><strong>${doneWords}/${totalWords}</strong><span>éléments vus</span></div><div class="metric"><strong>3+</strong><span>types d'exercices par leçon</span></div></div><div class="phase"><b>Étape 1 · Bases</b> — leçons 1 à 8</div><div class="phase"><b>Étape 2 · Vie quotidienne</b> — leçons 9 à 18</div><div class="phase"><b>Étape 3 · S'exprimer</b> — leçons 19 à 25</div><div class="phase"><b>Étape 4 · Expression orale</b> — leçons 26 à 29</div><div class="phase"><b>Étape 5 · Sproochentest</b> — leçon 30 + entraînements</div></div><div class="sectionTitle"><h3>Les 3 parties</h3><small>progressions distinctes</small></div><div class="skillCard"><h4>📘 Apprentissage</h4><p>30 leçons avec vocabulaire, mémorisation active et exercices de contexte.</p></div><div class="skillCard"><h4>🎧 Compréhension orale</h4><p>Mots entendus, puis phrases/dialogues et, plus tard, contenus authentiques.</p></div><div class="skillCard"><h4>🗣️ Expression orale</h4><p>Réponses à voix haute, présentation, description, récit et opinion.</p></div>`;progressText.textContent=`${done}/${lessons.length} leçons · ${pct}%`}

// Une leçon n'est plus seulement une liste de vocabulaire.
window.renderLessonWords=function(){const l=lessons[activeLesson];lessonContent.innerHTML=`<div class="card"><div class="lessonHead"><div class="lessonNo">${activeLesson+1}</div><div><div class="eyebrow">Leçon ${activeLesson+1}/${lessons.length}</div><h2 style="margin:4px 0">${l.title}</h2><div class="tiny">${l.words.length} éléments</div></div></div><div class="lessonPlan"><div><b>1</b>Apprendre</div><div><b>2</b>S'entraîner</div><div><b>3</b>Test complet</div></div></div><div class="card"><div class="tiny">À apprendre</div>${l.words.map((w,i)=>{const sid='ast-'+activeLesson+'-'+i;return `<div class="word"><div class="lux">${w[0]}</div><div class="fr">${w[1]}</div><div class="audioLine"><button class="audioBtn">🔊 Écouter</button><span class="audioStatus" id="${sid}">Voix humaine uniquement</span></div></div>`}).join('')}</div><button class="primary" onclick="startLessonPractice()">Passer aux exercices</button>`}

let practice=[],practiceIndex=0;
window.startLessonPractice=function(){const l=lessons[activeLesson],ws=shuffle(l.words.slice());practice=[];
// 1. rappel actif sans propositions
if(ws[0])practice.push({type:'🧠 Rappel actif',title:'Retrouve le sens',prompt:`Que signifie « ${ws[0][0]} » ?`,answer:ws[0][1],hint:'Réponds sans regarder la liste.'});
// 2. production FR -> lux sans proposition
if(ws[1]||ws[0]){const w=ws[1]||ws[0];practice.push({type:'✍️ Production',title:'Produis le luxembourgeois',prompt:`Comment dis-tu « ${w[1]} » ?`,answer:w[0],hint:'Aucune réponse suggérée.'})}
// 3. compréhension / contexte
const w3=ws[2]||ws[0];if(w3)practice.push({type:'🔎 Compréhension',title:'Comprends une petite situation',prompt:`Tu rencontres « ${w3[0]} » dans une phrase. Quel sens dois-tu reconnaître ?`,answer:w3[1],hint:'Cherche le sens utile, pas une traduction mot à mot compliquée.'});
// 4. oral systématique
practice.push({type:'🗣️ Expression orale',title:'Parle à voix haute',prompt:oralPrompts[activeLesson]||`Utilise au moins deux éléments de la leçon « ${l.title} » dans une réponse à voix haute.`,answer:'Auto-évalue surtout si les mots de la leçon te viennent sans regarder.',hint:'Parle réellement à voix haute avant de révéler.'});
practiceIndex=0;renderPractice()}
window.renderPractice=function(){if(practiceIndex>=practice.length){lessonContent.innerHTML=`<div class="card"><div class="eyebrow">Entraînement terminé</div><h2>Place au test complet</h2><p class="muted">Tous les éléments vont maintenant être testés dans les deux sens, dans un ordre mélangé.</p><button class="primary" onclick="startQuiz()">Commencer le test final</button></div>`;return}const p=practice[practiceIndex];lessonContent.innerHTML=`<div class="exerciseBox"><div class="exerciseType">${p.type}</div><div class="tiny">Exercice ${practiceIndex+1}/${practice.length}</div><h3>${p.title}</h3><div class="selfQ">${p.prompt}</div><p class="muted">${p.hint}</p><button class="primary" onclick="revealPractice()">Révéler / vérifier</button><div id="practiceAnswer"></div></div>`}
window.revealPractice=function(){const p=practice[practiceIndex];practiceAnswer.innerHTML=`<div class="reveal">${p.answer}</div><button class="primary" onclick="practiceIndex++;renderPractice()">Exercice suivant</button>`}

// Test final : tout le contenu, 2 sens, ordre mélangé, jamais le même item consécutivement si évitable.
let cards=[],cardIndex=0,selfGood=0,revealed=false;
function buildMixedCards(){const pool=[];lessons[activeLesson].words.forEach((w,id)=>{pool.push({id,prompt:w[0],answer:w[1],dir:'Luxembourgeois → français'});pool.push({id,prompt:w[1],answer:w[0],dir:'Français → luxembourgeois'})});shuffle(pool);const out=[];while(pool.length){const prev=out[out.length-1];let choices=pool.map((c,i)=>({c,i})).filter(x=>!prev||x.c.id!==prev.id);if(!choices.length)choices=pool.map((c,i)=>({c,i}));const pick=choices[Math.floor(Math.random()*choices.length)].i;out.push(pool.splice(pick,1)[0])}return out}
window.startQuiz=function(){cards=buildMixedCards();cardIndex=0;selfGood=0;renderSelfCard()}
window.renderSelfCard=function(){if(cardIndex>=cards.length){finishSelfTest();return}const c=cards[cardIndex];revealed=false;lessonContent.innerHTML=`<div class="card"><div class="eyebrow">Test complet · ${cardIndex+1}/${cards.length}</div><div class="tiny" style="margin-top:6px">${c.dir}</div><div class="selfQ">${c.prompt}</div><p class="muted">Réponds mentalement ou à voix haute. Aucune proposition n'est donnée.</p><button class="primary" onclick="revealSelf()">Révéler la réponse</button><div id="selfReveal"></div></div>`}
window.revealSelf=function(){if(revealed)return;revealed=true;const c=cards[cardIndex];selfReveal.innerHTML=`<div class="reveal">${c.answer}</div><div class="judge"><button class="no" onclick="judgeSelf(false)">À revoir</button><button class="yes" onclick="judgeSelf(true)">Je savais</button></div>`}
window.judgeSelf=function(ok){if(ok)selfGood++;cardIndex++;renderSelfCard()}
window.finishSelfTest=function(){const total=cards.length,pct=Math.round(selfGood/total*100),ok=pct>=80;if(ok&&!state.done.includes(activeLesson)){state.done.push(activeLesson);state.done.sort((a,b)=>a-b);save()}lessonContent.innerHTML=`<div class="card" style="text-align:center;padding:28px"><div style="font-size:48px">${ok?'✓':'↻'}</div><h2>${ok?'Leçon maîtrisée':'Encore à consolider'}</h2><p class="muted">${selfGood}/${total} réponses déclarées sues · ${pct} %. ${ok?'La leçon suivante est débloquée.':'Il faut 80 % pour valider.'}</p><button class="primary" onclick="${ok?"show('home')":"openLesson(activeLesson)"}">${ok?'Retour au parcours':'Revoir la leçon'}</button></div>`}

window.renderNews=function(){const done=state.done.length;newsGate.innerHTML=`<div class="card"><div class="eyebrow">🎧 Compréhension orale</div><h3>Parcours séparé</h3><p class="muted">Mots isolés → phrases courtes → dialogues → informations pratiques → extraits authentiques.</p><div class="progress"><span style="width:${Math.min(100,done/20*100)}%"></span></div><div class="tiny">La difficulté augmente avec les leçons maîtrisées.</div></div><div class="card"><div class="eyebrow">🗣️ Expression orale</div><h3>Parcours séparé</h3><div class="pathItem"><div class="dot">1</div><div><b>Se présenter</b><small>Nom, domicile, famille, travail, loisirs.</small></div></div><div class="pathItem"><div class="dot">2</div><div><b>Répondre spontanément</b><small>Questions sans choix ni texte à lire.</small></div></div><div class="pathItem"><div class="dot">3</div><div><b>Décrire et raconter</b><small>Image, situation, journée, passé et projets.</small></div></div><div class="pathItem"><div class="dot">4</div><div><b>Donner son avis</b><small>Réponse simple puis justification.</small></div></div></div>`}

document.querySelectorAll('.brand small').forEach(x=>x.textContent='Départ zéro · V19.5');document.title='Sproochentest Lëtzebuergesch V19.5';renderHome();
})();