// V19.6 — compréhension orale réelle avec phrases humaines LOD
(function(){
'use strict';
let oralPlayer=null;
const listening=[
 {min:0,title:'Habiter quelque part',audio:'https://lod.lu/uploads/examples/OGG/57/5708aa802f9771f2a431a9310f609b90.ogg',text:'ech wunnen zu Eech',source:'LOD · Eech',q:'Que dit la personne ?',opts:['Elle habite à Eech.','Elle travaille à Eech.','Elle quitte Eech.'],a:0,why:'« ech wunnen » signifie « j’habite ».'},
 {min:2,title:'Comprendre une question',audio:'https://lod.lu/uploads/examples/OGG/7a/7af2674e596a6c81e13aa53e3bfd8a89.ogg',text:'fiert dëse Bus op Eech?',source:'LOD · Eech',q:'Que demande la personne ?',opts:['Si ce bus va à Eech.','Combien coûte le bus.','À quelle heure ferme la gare.'],a:0,why:'« fiert dëse Bus op…? » demande si le bus va vers ce lieu.'},
 {min:5,title:'Gare et aéroport',audio:'https://lod.lu/uploads/examples/OGG/99/993dc701e65f000216eed16a3d7b4dc0.ogg',text:'déi nei Buslinn fiert vun der Gare op de Flughafen',source:'LOD · Buslinn',q:'Quel trajet est annoncé ?',opts:['De la gare à l’aéroport.','De l’aéroport au centre commercial.','De la maison à l’école.'],a:0,why:'« vun der Gare op de Flughafen » = de la gare vers l’aéroport.'},
 {min:8,title:'Au café',audio:'https://lod.lu/uploads/examples/OGG/bd/bd64bfea677c6f9acc314b9fd4ed0cb2.ogg',text:'mir hunn eng Taass Kaffi gedronk',source:'LOD · Kaffi',q:'Qu’ont-ils bu ?',opts:['Une tasse de café.','Un verre d’eau.','Une tasse de thé.'],a:0,why:'« eng Taass Kaffi » = une tasse de café.'},
 {min:10,title:'Comprendre un détail',audio:'https://lod.lu/uploads/examples/OGG/4c/4c4f9a38005924e30b5af0572dc95d29.ogg',text:'hien drénkt nëmme schwaarze Kaffi',source:'LOD · Kaffi',q:'Quel café boit-il ?',opts:['Uniquement du café noir.','Uniquement du café au lait.','Il ne boit jamais de café.'],a:0,why:'« nëmme schwaarze Kaffi » = seulement du café noir.'},
 {min:12,title:'La météo',audio:'https://lod.lu/uploads/examples/OGG/fe/fef9b02ea8a96664cdf7fb8ace799f71.ogg',text:'wa schéint Wieder ass, si vill Cyclisten op der Strooss',source:'LOD · Wieder',q:'Que se passe-t-il quand il fait beau ?',opts:['Il y a beaucoup de cyclistes sur la route.','Les bus ne circulent plus.','Tout le monde reste à la maison.'],a:0,why:'La phrase associe le beau temps à de nombreux cyclistes sur la route.'},
 {min:15,title:'Écouter la météo',audio:'https://lod.lu/uploads/examples/OGG/32/326d946b134d79ed507e0984cef18ad4.ogg',text:"maach de Radio méi haart, ech wëll d'Wieder lauschteren!",source:'LOD · Wieder',q:'Pourquoi faut-il monter le volume de la radio ?',opts:['Pour écouter la météo.','Pour écouter de la musique.','Pour téléphoner.'],a:0,why:'« ech wëll d’Wieder lauschteren » = je veux écouter la météo.'},
 {min:18,title:'Dans l’autobus',audio:'https://lod.lu/uploads/examples/OGG/5e/5e89147416f5f194d1231df26ec7d19c.ogg',text:'am Autobus sinn nach Sëtzplaze fräi',source:'LOD · Autobus',q:'Quelle information est donnée ?',opts:['Il reste des places assises libres dans le bus.','Le bus est complet.','Le bus est en retard.'],a:0,why:'« Sëtzplaze fräi » signifie que des places assises sont encore libres.'}
];

const speaking=[
 {min:0,title:'Saluer',prompt:'Salue quelqu’un puis dis au revoir, sans regarder le vocabulaire.',model:'Moien. … Äddi.'},
 {min:2,title:'Se présenter',prompt:'Dis ton prénom et où tu habites en deux phrases.',model:'Ech heeschen … Ech wunnen zu …'},
 {min:5,title:'Questions simples',prompt:'Pose une question avec « wou » puis une avec « wéi ».',model:'Wou …? / Wéi …?'},
 {min:8,title:'Famille',prompt:'Parle de deux personnes de ta famille avec des phrases très simples.',model:'Meng Mamm … / Mäi Papp …'},
 {min:12,title:'Vie quotidienne',prompt:'Dis ce que tu bois ou manges, puis comment tu te déplaces.',model:'Ech drénken … Ech fuere mam …'},
 {min:16,title:'Décrire',prompt:'Décris une personne ou un lieu avec au moins trois éléments appris.',model:'Réponse libre : priorité à des phrases simples et compréhensibles.'},
 {min:20,title:'Raconter',prompt:'Dis une chose faite hier puis un projet pour demain.',model:'Gëschter … Muer …'},
 {min:24,title:'Donner son avis',prompt:'Donne ton avis sur un loisir, un lieu ou une activité et justifie avec « well ».',model:'Fir mech …, well …'},
 {min:27,title:'Description d’image',prompt:'Imagine une photo : dis ce que tu vois devant, derrière et à côté.',model:'Virun … Hannert … Nieft …'},
 {min:29,title:'Stratégies au test',prompt:'Demande de répéter puis de parler plus lentement.',model:'Kënnt Dir dat widderhuelen? / Méi lues, wann ech gelift.'}
];

const css=document.createElement('style');css.textContent=`
.oralTabs{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:12px 0}.oralTabs button{padding:12px;border-radius:13px;background:#eef2f6;color:#526174;font-weight:800}.oralTabs button.active{background:var(--blue2);color:var(--blue)}
.oralItem{padding:16px;border:1px solid var(--line);border-radius:17px;background:#fff;margin:10px 0}.oralItem.locked{opacity:.48}.oralItem h4{margin:0 0 6px}.listenBtn{width:100%;padding:14px;border-radius:14px;background:var(--blue);color:#fff;font-weight:850;margin:10px 0}.oralChoice{display:block;width:100%;text-align:left;padding:12px;border-radius:12px;background:#f5f7fa;border:1px solid var(--line);margin:7px 0;color:var(--ink)}.oralChoice.good{background:var(--green2);border-color:#9cdbbd}.oralChoice.bad{background:var(--red2);border-color:#f2adb4}.transcript{padding:13px;border-radius:13px;background:#f4f6f9;margin-top:10px;line-height:1.45}.sourceNote{font-size:11px;color:var(--muted);margin-top:7px}.oralScore{font-size:12px;color:var(--muted);margin-top:8px}
`;document.head.appendChild(css);

let oralMode='listen',activeListening=null;
function doneCount(){return Array.isArray(state?.done)?state.done.length:0}
function playSentence(i,btn){const x=listening[i];if(doneCount()<x.min)return;try{oralPlayer?.pause();oralPlayer=new Audio(x.audio);btn.textContent='🔊 Lecture…';oralPlayer.play().then(()=>{oralPlayer.onended=()=>btn.textContent='▶ Écouter la phrase'}).catch(()=>{btn.textContent='Réessayer';});}catch(e){btn.textContent='Réessayer'}}
function answerListening(i,choice,btn){const x=listening[i],box=btn.closest('.oralItem'),buttons=box.querySelectorAll('.oralChoice');buttons.forEach((b,j)=>{b.disabled=true;if(j===x.a)b.classList.add('good')});if(choice!==x.a)btn.classList.add('bad');const reveal=box.querySelector('.oralReveal');reveal.innerHTML=`<div class="transcript"><b>Transcription :</b><br>${x.text}<br><br><b>Pourquoi :</b> ${x.why}</div><div class="sourceNote">Audio humain : ${x.source}</div>`}
window.playListening=playSentence;window.answerListening=answerListening;

function renderListening(){const d=doneCount();return `<div class="card"><div class="eyebrow">🎧 Compréhension orale</div><h3>Écoute d’abord, texte ensuite</h3><p class="muted">La transcription reste cachée jusqu’à la réponse. Les phrases sont de vrais enregistrements humains du LOD.</p><div class="progress"><span style="width:${Math.min(100,d/20*100)}%"></span></div><div class="tiny">${listening.filter(x=>d>=x.min).length}/${listening.length} exercices débloqués</div></div>`+listening.map((x,i)=>{const locked=d<x.min;return `<div class="oralItem ${locked?'locked':''}"><div class="tiny">${locked?'🔒 Se débloque après '+x.min+' leçons':'Niveau accessible'}</div><h4>${x.title}</h4>${locked?'<p class="muted">Continue le parcours principal pour débloquer cet exercice.</p>':`<button class="listenBtn" onclick="playListening(${i},this)">▶ Écouter la phrase</button><div class="selfQ" style="font-size:18px;margin:12px 0">${x.q}</div>${x.opts.map((o,j)=>`<button class="oralChoice" onclick="answerListening(${i},${j},this)">${o}</button>`).join('')}<div class="oralReveal"></div>`}</div>`}).join('')}
function renderSpeaking(){const d=doneCount();return `<div class="card"><div class="eyebrow">🗣️ Expression orale</div><h3>Parler sans lire une réponse</h3><p class="muted">Tu réponds réellement à voix haute. Le modèle n’apparaît qu’après que tu as essayé.</p></div>`+speaking.map((x,i)=>{const locked=d<x.min;return `<div class="oralItem ${locked?'locked':''}"><div class="tiny">${locked?'🔒 Se débloque après '+x.min+' leçons':'Exercice '+(i+1)}</div><h4>${x.title}</h4>${locked?'<p class="muted">Pas encore : consolide d’abord les bases.</p>':`<div class="selfQ" style="font-size:18px">${x.prompt}</div><button class="primary" onclick="this.nextElementSibling.style.display='block';this.style.display='none'">J’ai répondu · voir un modèle</button><div class="transcript" style="display:none"><b>Exemple possible :</b><br>${x.model}<div class="judge"><button class="no" onclick="this.closest('.oralItem').querySelector('.oralScore').textContent='À revoir : refais cet exercice plus tard.'">À revoir</button><button class="yes" onclick="this.closest('.oralItem').querySelector('.oralScore').textContent='Acquis pour aujourd’hui.'">Je savais répondre</button></div></div><div class="oralScore"></div>`}</div>`}).join('')}
window.setOralMode=function(mode){oralMode=mode;renderNews()};
window.renderNews=function(){newsGate.innerHTML=`<div class="oralTabs"><button class="${oralMode==='listen'?'active':''}" onclick="setOralMode('listen')">🎧 Compréhension</button><button class="${oralMode==='speak'?'active':''}" onclick="setOralMode('speak')">🗣️ Expression</button></div>${oralMode==='listen'?renderListening():renderSpeaking()}`};

document.querySelectorAll('.brand small').forEach(x=>x.textContent='Départ zéro · V19.6');document.title='Sproochentest Lëtzebuergesch V19.6';
})();