// V20.18 — RTL : transcription progressive par petits blocs, sans charger 20 min en mémoire
(function(){
'use strict';
const VERSION='V20.18';
const RTL_FR='https://play.rtl.lu/shows/fr/journal/episodes';
const VOCAB_KEY='sproochentest-rtl-vocab-v1';
const episodes=[
 {date:'07/08/2026',duration:'22 min 42 s',url:'https://play.rtl.lu/shows/fr/journal/episodes/r/3469221'},
 {date:'06/08/2026',duration:'18 min 01 s',url:'https://play.rtl.lu/shows/fr/journal/episodes/r/3469187'},
 {date:'05/08/2026',duration:'18 min 54 s',url:'https://play.rtl.lu/shows/fr/journal/episodes/r/3469107'}
];
let selected=null,chunks=[],transcriber=null,recorder=null,recording=false,queue=[],processing=false,blockStart=0;
const css=document.createElement('style');
css.textContent=`
.rtlEp{padding:14px;border:1px solid var(--line);border-radius:15px;margin:9px 0;background:#fff;cursor:pointer}.rtlEp.active{border-color:#67aee7;background:#f3f9ff}.rtlEp b{display:block}.rtlEp small{color:var(--muted)}.rtlPlayer{position:relative;border-radius:16px;overflow:hidden;background:#000;margin-top:12px}.rtlPlayer video{display:block;width:100%;max-height:64vh;background:#000}.rtlLuSub{position:absolute;left:4%;right:4%;top:6%;z-index:4;text-align:center;color:#fff;font-size:clamp(17px,4.5vw,25px);font-weight:900;line-height:1.25;text-shadow:0 2px 5px #000,0 0 8px #000;background:#0008;border-radius:10px;padding:7px 10px;pointer-events:none}.rtlActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rtlActions button,.rtlActions a{padding:10px 12px;border-radius:12px;background:var(--blue2);color:#115c9f;font-weight:800;text-decoration:none}.rtlActions .go{background:var(--blue);color:#fff}.rtlActions button:disabled{opacity:.55}.rtlStatus{margin-top:9px;padding:10px 12px;border-radius:12px;background:#f4f6f9;color:var(--muted);font-size:13px;line-height:1.4}.rtlStatus strong{color:var(--ink)}.rtlTranscript{max-height:230px;overflow:auto;margin-top:10px}.rtlLine{padding:9px 0;border-bottom:1px solid var(--line);font-size:14px;line-height:1.35}.rtlLine time{color:var(--muted);font-size:11px;margin-right:7px}.rtlVocab{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.rtlWord{padding:8px 10px;border-radius:11px;background:#f1f5f9;border:1px solid var(--line);font-weight:750}.rtlWord.saved{background:var(--green2);color:var(--green)}
`;
document.head.appendChild(css);
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function status(text){const s=document.getElementById('rtlStatus');if(s)s.innerHTML=text}
function pick360(media){return media.find(x=>/360p\.mp4/i.test(x))||media.find(x=>/480p\.mp4/i.test(x))||media.find(x=>/\.mp4/i.test(x))||media.find(x=>/\.m3u8/i.test(x))}
async function loadEpisode(i){
 stopCapture();selected=episodes[i];chunks=[];queue=[];document.querySelectorAll('.rtlEp').forEach((e,j)=>e.classList.toggle('active',j===i));status('<strong>Chargement de la vidéo RTL…</strong>');
 try{const r=await fetch('/api/rtl-meta?url='+encodeURIComponent(selected.url));const data=await r.json();if(!r.ok||!data.ok)throw new Error(data.error||'RTL indisponible');const media=pick360(data.media||[]);if(!media)throw new Error('Flux vidéo introuvable');const v=document.getElementById('rtlVideo');v.crossOrigin='anonymous';v.src=media;v.load();document.getElementById('rtlOriginal').href=selected.url;document.getElementById('rtlTitle').textContent='Journal du '+selected.date;document.getElementById('rtlLuSub').textContent='';document.getElementById('rtlTranscript').innerHTML='';document.getElementById('rtlVocab').innerHTML='';status('Vidéo prête. Appuie sur <strong>Activer les sous-titres LU</strong>, puis lance la vidéo. La transcription se fera par petits blocs pendant la lecture, sans charger tout le journal en mémoire.')}catch(e){status('<strong>Erreur :</strong> '+esc(e.message))}
}
async function getTranscriber(){if(transcriber)return transcriber;status('<strong>Premier lancement :</strong> téléchargement du petit modèle Whisper. Cela peut prendre un moment, mais ne doit plus charger toute la vidéo.');const mod=await import('https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1');mod.env.allowLocalModels=false;transcriber=await mod.pipeline('automatic-speech-recognition','Xenova/whisper-tiny');return transcriber}
async function blobTo16k(blob){const ab=await blob.arrayBuffer();const C=window.AudioContext||window.webkitAudioContext;const ctx=new C();const decoded=await ctx.decodeAudioData(ab.slice(0));const len=Math.ceil(decoded.duration*16000);const off=new OfflineAudioContext(1,len,16000);const src=off.createBufferSource();src.buffer=decoded;src.connect(off.destination);src.start();const rendered=await off.startRendering();await ctx.close();return rendered.getChannelData(0).slice()}
function addOutput(out,start){const list=(out&&out.chunks)||[];if(list.length){list.forEach(c=>{const ts=Array.isArray(c.timestamp)?c.timestamp:[0,4];const a=Number(ts[0]||0)+start;let b=Number(ts[1]);if(!Number.isFinite(b))b=Number(ts[0]||0)+4;b+=start;const text=String(c.text||'').trim();if(text)chunks.push({start:a,end:b,text})})}else if(out&&out.text){chunks.push({start:start,end:start+20,text:String(out.text).trim()})}chunks.sort((a,b)=>a.start-b.start);renderTranscript()}
async function processQueue(){if(processing)return;processing=true;try{const pipe=await getTranscriber();while(queue.length){const item=queue.shift();status('<strong>Sous-titres LU actifs.</strong> Transcription du passage '+fmt(item.start)+'… La vidéo peut continuer.');try{const audio=await blobTo16k(item.blob);const out=await pipe(audio,{language:'luxembourgish',task:'transcribe',return_timestamps:true,chunk_length_s:20});addOutput(out,item.start)}catch(e){console.warn('RTL LU bloc ignoré',e)}}if(recording)status('<strong>Sous-titres LU actifs.</strong> La transcription continue automatiquement pendant la lecture.')}finally{processing=false}}
function fmt(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
async function startCapture(){const v=document.getElementById('rtlVideo'),btn=document.getElementById('rtlTranscribe');if(!selected||!v.src){status('Choisis d’abord un journal.');return}if(recording){stopCapture();return}btn.disabled=true;try{await getTranscriber();const capture=v.captureStream||v.mozCaptureStream;if(!capture)throw new Error('La capture audio de la vidéo n’est pas disponible dans ce navigateur.');const stream=capture.call(v);const audioTracks=stream.getAudioTracks();if(!audioTracks.length)throw new Error('Le flux RTL ne permet pas de récupérer l’audio pour la transcription locale.');const audioStream=new MediaStream(audioTracks);let options={};if(MediaRecorder.isTypeSupported('audio/webm;codecs=opus'))options={mimeType:'audio/webm;codecs=opus'};recorder=new MediaRecorder(audioStream,options);recorder.ondataavailable=e=>{if(e.data&&e.data.size>1000){queue.push({blob:e.data,start:blockStart});blockStart=v.currentTime;processQueue()}};recorder.onerror=e=>status('<strong>Erreur de capture :</strong> '+esc(e.error?.message||'inconnue'));blockStart=v.currentTime;recorder.start(20000);recording=true;btn.textContent='Arrêter les sous-titres LU';status('<strong>Prêt.</strong> Lance ou reprends la vidéo. Un petit bloc audio sera transcrit toutes les 20 secondes, ce qui évite le freeze.')}catch(e){status('<strong>Impossible d’activer les sous-titres LU :</strong> '+esc(e.message))}finally{btn.disabled=false}}
function stopCapture(){recording=false;if(recorder&&recorder.state!=='inactive'){try{recorder.stop()}catch(e){}}recorder=null;const b=document.getElementById('rtlTranscribe');if(b)b.textContent='Activer les sous-titres LU gratuitement'}
function renderTranscript(){const box=document.getElementById('rtlTranscript');if(box)box.innerHTML=chunks.map(c=>`<div class="rtlLine"><time>${fmt(c.start)}</time>${esc(c.text)}</div>`).join('');buildVocab(chunks.map(x=>x.text).join(' '))}
function buildVocab(text){const stop=new Set('déi deen den dem der an am op um vun fir mat ass sinn war waren huet hunn gëtt ginn sech net och nach wéi wat wou wien wann well do hei elo haut méi ganz vill dës dëst een eng engem enger zu ze bei no vir iwwer ënner oder mee mä als dass ech du hien hatt mir dir eis iech'.split(' '));const m=new Map();(text.toLowerCase().match(/[a-zà-ÿäëéèêöüß’'-]{4,}/gi)||[]).forEach(w=>{w=w.replace(/[’'-]+$/,'');if(!stop.has(w))m.set(w,(m.get(w)||0)+1)});const words=[...m].sort((a,b)=>b[1]-a[1]).slice(0,14).map(x=>x[0]);const saved=readSaved();const box=document.getElementById('rtlVocab');if(!box)return;box.innerHTML=words.map(w=>`<button class="rtlWord ${saved.some(s=>s.lu===w)?'saved':''}" data-w="${esc(w)}">${esc(w)}</button>`).join('');box.querySelectorAll('.rtlWord').forEach(b=>b.onclick=()=>saveWord(b.dataset.w,b))}
function readSaved(){try{return JSON.parse(localStorage.getItem(VOCAB_KEY)||'[]')}catch(e){return[]}}
function saveWord(w,b){const a=readSaved();if(!a.some(x=>x.lu===w))a.push({lu:w,fr:'À réviser',source:selected?'Journal du '+selected.date:'RTL',added:Date.now()});localStorage.setItem(VOCAB_KEY,JSON.stringify(a));b.classList.add('saved')}
function sync(){const v=document.getElementById('rtlVideo'),sub=document.getElementById('rtlLuSub');if(!v||!sub)return;const t=v.currentTime,c=chunks.find(x=>t>=x.start&&t<(x.end||x.start+5));sub.textContent=c?c.text:''}
function render(){if(!window.newsGate)return;newsGate.innerHTML=`<div class="card"><div class="eyebrow">RTL · double sous-titrage gratuit</div><h3 style="margin:6px 0">Choisir un journal</h3><p class="muted">Le français reste incrusté par RTL. Le luxembourgeois est généré localement par petits blocs pendant la lecture pour éviter de saturer la mémoire du téléphone.</p>${episodes.map((e,i)=>`<div class="rtlEp" onclick="v218Load(${i})"><b>Journal du ${e.date}</b><small>${e.duration}</small></div>`).join('')}</div><div class="card"><div class="eyebrow">Lecture bilingue</div><h3 id="rtlTitle" style="margin:6px 0">Choisis un journal</h3><div class="rtlPlayer"><video id="rtlVideo" controls playsinline></video><div id="rtlLuSub" class="rtlLuSub"></div></div><div class="rtlActions"><button id="rtlTranscribe" class="go">Activer les sous-titres LU gratuitement</button><a id="rtlOriginal" href="${RTL_FR}" target="_blank" rel="noopener">Ouvrir sur RTL</a></div><div id="rtlStatus" class="rtlStatus">Cette version ne télécharge plus le journal entier pour le transcrire.</div><div id="rtlTranscript" class="rtlTranscript"></div><div id="rtlVocab" class="rtlVocab"></div></div>`;document.getElementById('rtlTranscribe').onclick=startCapture;const v=document.getElementById('rtlVideo');v.addEventListener('timeupdate',sync);v.addEventListener('ended',stopCapture)}
window.v218Load=loadEpisode;window.renderNews=render;
document.querySelectorAll('.brand small').forEach(x=>x.textContent=VERSION+' · RTL bilingue progressif gratuit');document.title='Sproochentest Lëtzebuergesch '+VERSION;
})();