// V20.22 — préparation complète LuxASR sans lecture + sous-titre LU sous la vidéo
(function(){
'use strict';
const VERSION='V20.22';let busy=false;let syncOffset=Number(localStorage.getItem('rtl-lu-sync-offset')||0);
const css=document.createElement('style');css.textContent=`
.rtlLuSub{display:none!important}.rtlLuBelow{min-height:54px;margin-top:8px;padding:10px 12px;border-radius:12px;background:#101418;color:#fff;text-align:center;font-size:clamp(16px,4.2vw,22px);font-weight:850;line-height:1.3;display:flex;align-items:center;justify-content:center}.rtlFullNote{font-size:12px;color:var(--muted);margin-top:7px}
`;document.head.appendChild(css);
function sec(s){const p=String(s||'').replace(',','.').split(':').map(Number);return (p[0]||0)*3600+(p[1]||0)*60+(p[2]||0)}
function fmt(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function parseVtt(vtt){const out=[];for(const b of String(vtt||'').replace(/\r/g,'').split(/\n\n+/)){const l=b.split('\n').filter(Boolean),i=l.findIndex(x=>x.includes('-->'));if(i<0)continue;const [a,z]=l[i].split('-->').map(x=>x.trim().split(/\s+/)[0]);const text=l.slice(i+1).join(' ').replace(/<[^>]+>/g,'').trim();if(text)out.push({start:sec(a),end:sec(z),text})}return out}
function episodeId(){const h=document.getElementById('rtlOriginal')?.href||'';return (h.match(/\/r\/(\d+)/)||[])[1]||''}
function cacheKey(){const id=episodeId();return id?'sproochentest-rtl-full-vtt-'+id:''}
function setStatus(t){const s=document.getElementById('rtlStatus');if(s)s.innerHTML=t}
function renderLines(lines){const box=document.getElementById('rtlTranscript');if(!box)return;box.innerHTML=lines.map(c=>`<div class="rtlLine" data-end="${c.end}"><time>${fmt(c.start)}</time>${String(c.text).replace(/[&<>]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[m]))}</div>`).join('')}
function getLines(){const box=document.getElementById('rtlTranscript');if(!box)return[];return [...box.querySelectorAll('.rtlLine')].map(el=>{const tm=el.querySelector('time');const start=sec('0:'+String(tm?.textContent||'0:00'));const text=el.textContent.replace(tm?.textContent||'','').trim();const end=Number(el.dataset.end)||null;return{start,end,text}}).filter(x=>x.text).sort((a,b)=>a.start-b.start)}
function draw(){const v=document.getElementById('rtlVideo'),bar=document.getElementById('rtlLuBelow');if(!v||!bar)return;const lines=getLines(),t=v.currentTime+syncOffset;let c=null;for(let i=0;i<lines.length;i++){const end=lines[i].end||lines[i+1]?.start||lines[i].start+6;if(t>=lines[i].start&&t<end){c=lines[i];break}}bar.textContent=c?c.text:''}
async function poll(id){for(let i=0;i<180;i++){await new Promise(r=>setTimeout(r,2000));const r=await fetch('/api/luxasr-job?id='+encodeURIComponent(id),{cache:'no-store'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Suivi LuxASR impossible');if(d.status==='completed')return d.vtt;if(d.status==='failed')throw new Error('LuxASR a échoué');setStatus('<strong>LuxASR traite tout le journal en arrière-plan…</strong><br>Tu peux laisser la vidéo en pause. État : '+d.status)}throw new Error('LuxASR met trop de temps')}
async function prepareFull(){if(busy)return;const href=document.getElementById('rtlOriginal')?.href,btn=document.getElementById('rtlPrepare');if(!href||!/\/r\/\d+/.test(href)){setStatus('Choisis d’abord un journal.');return}busy=true;if(btn){btn.disabled=true;btn.textContent='Préparation complète…'}try{setStatus('<strong>Envoi du journal complet à LuxASR…</strong><br>La vidéo n’a pas besoin d’être lue.');const r=await fetch('/api/luxasr-full-submit?url='+encodeURIComponent(href),{method:'POST'});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Envoi LuxASR impossible');const vtt=await poll(d.job_id),lines=parseVtt(vtt);if(!lines.length)throw new Error('Aucun sous-titre reçu');localStorage.setItem(cacheKey(),JSON.stringify(lines));renderLines(lines);document.getElementById('rtlVideo').currentTime=0;draw();setStatus('<strong>Tout le journal est prêt.</strong> Lance la vidéo : le français reste dans l’image RTL et le luxembourgeois s’affiche juste en dessous, au même moment.')}catch(e){setStatus('<strong>Préparation complète impossible :</strong> '+e.message)}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='Préparer tout le journal avec LuxASR'}}}
function install(){const v=document.getElementById('rtlVideo'),player=document.querySelector('.rtlPlayer'),btn=document.getElementById('rtlPrepare');if(!v||!player||!btn)return;if(!document.getElementById('rtlLuBelow')){const bar=document.createElement('div');bar.id='rtlLuBelow';bar.className='rtlLuBelow';player.insertAdjacentElement('afterend',bar)}btn.textContent='Préparer tout le journal avec LuxASR';btn.onclick=prepareFull;const note=document.createElement('div');note.className='rtlFullNote';note.textContent='Préparation en une fois : la vidéo peut rester en pause.';btn.parentElement?.insertAdjacentElement('afterend',note);const k=cacheKey();if(k){try{const a=JSON.parse(localStorage.getItem(k)||'null');if(Array.isArray(a)&&a.length){renderLines(a);setStatus('<strong>Journal déjà préparé en entier.</strong> Tu peux lancer la vidéo.')}}catch(e){}}v.addEventListener('timeupdate',draw);v.addEventListener('seeked',draw);v.addEventListener('play',draw);const syncButtons=document.querySelector('.rtlSync');if(syncButtons){syncButtons.addEventListener('click',()=>setTimeout(()=>{syncOffset=Number(localStorage.getItem('rtl-lu-sync-offset')||0);draw()},0))}}
const oldRender=window.renderNews;window.renderNews=function(){if(typeof oldRender==='function')oldRender();setTimeout(install,30)};
document.querySelectorAll('.brand small').forEach(x=>x.textContent=VERSION+' · RTL complet LuxASR');document.title='Sproochentest Lëtzebuergesch '+VERSION;
})();