// V20.20 — RTL : sous-titres luxembourgeois avec LuxASR (Université du Luxembourg)
(function(){
'use strict';
const VERSION='V20.20';
const RTL_FR='https://play.rtl.lu/shows/fr/journal/episodes';
const VOCAB_KEY='sproochentest-rtl-vocab-v1';
const SUB_KEY_PREFIX='sproochentest-rtl-luxasr-v2-';
const episodes=[
 {id:'3469221',date:'07/08/2026',duration:'22 min 42 s',url:'https://play.rtl.lu/shows/fr/journal/episodes/r/3469221'},
 {id:'3469187',date:'06/08/2026',duration:'18 min 01 s',url:'https://play.rtl.lu/shows/fr/journal/episodes/r/3469187'},
 {id:'3469107',date:'05/08/2026',duration:'18 min 54 s',url:'https://play.rtl.lu/shows/fr/journal/episodes/r/3469107'}
];
let selected=null,chunks=[],busy=false;
const css=document.createElement('style');css.textContent=`
.rtlEp{padding:14px;border:1px solid var(--line);border-radius:15px;margin:9px 0;background:#fff;cursor:pointer}.rtlEp.active{border-color:#67aee7;background:#f3f9ff}.rtlEp b{display:block}.rtlEp small{color:var(--muted)}.rtlPlayer{position:relative;border-radius:16px;overflow:hidden;background:#000;margin-top:12px}.rtlPlayer video{display:block;width:100%;max-height:64vh;background:#000}.rtlLuSub{position:absolute;left:4%;right:4%;top:6%;z-index:4;text-align:center;color:#fff;font-size:clamp(17px,4.5vw,25px);font-weight:900;line-height:1.25;text-shadow:0 2px 5px #000,0 0 8px #000;background:#0008;border-radius:10px;padding:7px 10px;pointer-events:none}.rtlActions{display:flex;gap:8px;flex-wrap:wrap;margin-top:10px}.rtlActions button,.rtlActions a{padding:10px 12px;border-radius:12px;background:var(--blue2);color:#115c9f;font-weight:800;text-decoration:none}.rtlActions .go{background:var(--blue);color:#fff}.rtlActions button:disabled{opacity:.55}.rtlStatus{margin-top:9px;padding:10px 12px;border-radius:12px;background:#f4f6f9;color:var(--muted);font-size:13px;line-height:1.4}.rtlStatus strong{color:var(--ink)}.rtlProgress{height:8px;background:#e5eaf1;border-radius:99px;overflow:hidden;margin-top:8px}.rtlProgress span{display:block;height:100%;background:var(--blue);width:0%}.rtlTranscript{max-height:230px;overflow:auto;margin-top:10px}.rtlLine{padding:9px 0;border-bottom:1px solid var(--line);font-size:14px;line-height:1.35}.rtlLine time{color:var(--muted);font-size:11px;margin-right:7px}.rtlVocab{display:flex;gap:7px;flex-wrap:wrap;margin-top:9px}.rtlWord{padding:8px 10px;border-radius:11px;background:#f1f5f9;border:1px solid var(--line);font-weight:750}.rtlWord.saved{background:var(--green2);color:var(--green)}`;document.head.appendChild(css);
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function status(text,pct){const s=document.getElementById('rtlStatus');if(s)s.innerHTML=text+(pct==null?'':`<div class="rtlProgress"><span style="width:${pct}%"></span></div>`)}
function fmt(t){return Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0')}
function pick360(media){return media.find(x=>/360p\.mp4/i.test(x))||media.find(x=>/480p\.mp4/i.test(x))||media.find(x=>/\.mp4/i.test(x))||media.find(x=>/\.m3u8/i.test(x))}
function cacheKey(){return selected?SUB_KEY_PREFIX+selected.id:null}
function saveCached(){try{localStorage.setItem(cacheKey(),JSON.stringify(chunks))}catch(e){}}
function loadCached(){try{const a=JSON.parse(localStorage.getItem(cacheKey())||'null');if(Array.isArray(a)&&a.length){chunks=a;renderTranscript();status('<strong>Sous-titres LuxASR déjà prêts.</strong> Lance la vidéo.',100);return true}}catch(e){}return false}
async function loadEpisode(i){selected=episodes[i];chunks=[];document.querySelectorAll('.rtlEp').forEach((e,j)=>e.classList.toggle('active',j===i));status('<strong>Chargement de la vidéo RTL…</strong>',5);try{const r=await fetch('/api/rtl-meta?url='+encodeURIComponent(selected.url));const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'RTL indisponible');const media=pick360(d.media||[]);if(!media)throw new Error('Flux vidéo introuvable');const v=document.getElementById('rtlVideo');v.crossOrigin='anonymous';v.src=media;v.load();document.getElementById('rtlOriginal').href=selected.url;document.getElementById('rtlTitle').textContent='Journal du '+selected.date;document.getElementById('rtlLuSub').textContent='';document.getElementById('rtlTranscript').innerHTML='';document.getElementById('rtlVocab').innerHTML='';if(!loadCached())status('Cette version n’utilise plus le petit Whisper générique. Appuie sur <strong>Préparer avec LuxASR</strong> : les passages audio sont reconnus par le système luxembourgeois de l’Université du Luxembourg.',100)}catch(e){status('<strong>Erreur :</strong> '+esc(e.message))}}
async function captureRange(v,start,duration){v.pause();v.currentTime=start;await new Promise((resolve,reject)=>{const ok=()=>{clean();resolve()},bad=()=>{clean();reject(new Error('Positionnement vidéo impossible'))},clean=()=>{v.removeEventListener('seeked',ok);v.removeEventListener('error',bad)};v.addEventListener('seeked',ok,{once:true});v.addEventListener('error',bad,{once:true})});const cap=(v.captureStream||v.mozCaptureStream);if(!cap)throw new Error('Capture audio non disponible sur ce navigateur');const tracks=cap.call(v).getAudioTracks();if(!tracks.length)throw new Error('Audio RTL inaccessible');const mime=MediaRecorder.isTypeSupported('audio/webm;codecs=opus')?'audio/webm;codecs=opus':'audio/webm';const rec=new MediaRecorder(new MediaStream(tracks),{mimeType:mime});const parts=[];rec.ondataavailable=e=>{if(e.data?.size)parts.push(e.data)};rec.start();await v.play();await new Promise(r=>setTimeout(r,duration*1000));v.pause();await new Promise(r=>{rec.onstop=r;rec.stop()});return new Blob(parts,{type:mime})}
function sec(s){const p=s.replace(',','.').split(':').map(Number);return (p[0]||0)*3600+(p[1]||0)*60+(p[2]||0)}
function parseVtt(vtt,offset){const out=[];const blocks=String(vtt||'').replace(/\r/g,'').split(/\n\n+/);for(const b of blocks){const lines=b.split('\n').filter(Boolean);const ti=lines.findIndex(x=>x.includes('-->'));if(ti<0)continue;const [a,z]=lines[ti].split('-->').map(x=>x.trim().split(/\s+/)[0]);const text=lines.slice(ti+1).join(' ').replace(/<[^>]+>/g,'').trim();if(text)out.push({start:offset+sec(a),end:offset+sec(z),text})}return out}
async function luxasr(blob){const r=await fetch('/api/luxasr',{method:'POST',headers:{'Content-Type':blob.type||'audio/webm'},body:blob});const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'LuxASR indisponible');return d.vtt}
async function prepare(){if(busy)return;const v=document.getElementById('rtlVideo'),btn=document.getElementById('rtlPrepare');if(!selected||!v.src){status('Choisis d’abord un journal.');return}busy=true;btn.disabled=true;chunks=[];renderTranscript();try{await new Promise(r=>{if(Number.isFinite(v.duration)&&v.duration>0)return r();v.addEventListener('loadedmetadata',r,{once:true})});const total=Math.floor(v.duration||0);if(!total)throw new Error('Durée vidéo inconnue');const step=20;for(let start=0;start<total;start+=step){const dur=Math.min(step,total-start),pct=Math.round(start/total*100);status('<strong>LuxASR prépare le luxembourgeois…</strong> '+fmt(start)+' / '+fmt(total),pct);const blob=await captureRange(v,start,dur);const vtt=await luxasr(blob);chunks.push(...parseVtt(vtt,start));chunks.sort((a,b)=>a.start-b.start);renderTranscript()}saveCached();v.currentTime=0;status('<strong>Terminé.</strong> Lance la vidéo : le texte luxembourgeois est synchronisé avec les timecodes LuxASR et le français reste celui incrusté par RTL.',100)}catch(e){status('<strong>Préparation interrompue :</strong> '+esc(e.message))}finally{busy=false;btn.disabled=false}}
function renderTranscript(){const box=document.getElementById('rtlTranscript');if(box)box.innerHTML=chunks.map(c=>`<div class="rtlLine"><time>${fmt(c.start)}</time>${esc(c.text)}</div>`).join('');buildVocab(chunks.map(x=>x.text).join(' '))}
function buildVocab(text){const stop=new Set('déi deen den dem der an am op um vun fir mat ass sinn war waren huet hunn gëtt ginn sech net och nach wéi wat wou wien wann well do hei elo haut méi ganz vill dës dëst een eng engem enger zu ze bei no vir iwwer ënner oder mee mä als dass ech du hien hatt mir dir eis iech'.split(' '));const m=new Map();(text.toLowerCase().match(/[a-zà-ÿäëéèêöüß’\'-]{4,}/gi)||[]).forEach(w=>{w=w.replace(/[’\'-]+$/,'');if(!stop.has(w))m.set(w,(m.get(w)||0)+1)});const words=[...m].sort((a,b)=>b[1]-a[1]).slice(0,14).map(x=>x[0]),saved=readSaved(),box=document.getElementById('rtlVocab');if(!box)return;box.innerHTML=words.map(w=>`<button class="rtlWord ${saved.some(s=>s.lu===w)?'saved':''}" data-w="${esc(w)}">${esc(w)}</button>`).join('');box.querySelectorAll('.rtlWord').forEach(b=>b.onclick=()=>saveWord(b.dataset.w,b))}
function readSaved(){try{return JSON.parse(localStorage.getItem(VOCAB_KEY)||'[]')}catch(e){return[]}}
function saveWord(w,b){const a=readSaved();if(!a.some(x=>x.lu===w))a.push({lu:w,fr:'À réviser',source:selected?'Journal du '+selected.date:'RTL',added:Date.now()});localStorage.setItem(VOCAB_KEY,JSON.stringify(a));b.classList.add('saved')}
function sync(){const v=document.getElementById('rtlVideo'),sub=document.getElementById('rtlLuSub');if(!v||!sub)return;const t=v.currentTime,c=chunks.find(x=>t>=x.start&&t<(x.end||x.start+5));sub.textContent=c?c.text:''}
function render(){if(!window.newsGate)return;newsGate.innerHTML=`<div class="card"><div class="eyebrow">RTL + LuxASR</div><h3 style="margin:6px 0">Choisir un journal</h3><p class="muted">Le français est celui de RTL. Le luxembourgeois est reconnu par LuxASR, spécialisé en luxembourgeois, puis synchronisé avec la vidéo.</p>${episodes.map((e,i)=>`<div class="rtlEp" onclick="v220Load(${i})"><b>Journal du ${e.date}</b><small>${e.duration}</small></div>`).join('')}</div><div class="card"><div class="eyebrow">Lecture bilingue</div><h3 id="rtlTitle" style="margin:6px 0">Choisis un journal</h3><div class="rtlPlayer"><video id="rtlVideo" controls playsinline></video><div id="rtlLuSub" class="rtlLuSub"></div></div><div class="rtlActions"><button id="rtlPrepare" class="go">Préparer avec LuxASR</button><a id="rtlOriginal" href="${RTL_FR}" target="_blank" rel="noopener">Ouvrir sur RTL</a></div><div id="rtlStatus" class="rtlStatus">Les anciens sous-titres erronés ne sont plus réutilisés.</div><div id="rtlTranscript" class="rtlTranscript"></div><div id="rtlVocab" class="rtlVocab"></div></div>`;document.getElementById('rtlPrepare').onclick=prepare;document.getElementById('rtlVideo').addEventListener('timeupdate',sync)}
window.v220Load=loadEpisode;window.renderNews=render;document.querySelectorAll('.brand small').forEach(x=>x.textContent=VERSION+' · RTL + LuxASR');document.title='Sproochentest Lëtzebuergesch '+VERSION;
})();