// V20.26 — application recentrée : vocabulaire + RTL + conversation + images + simulation
(function(){
'use strict';
const VERSION='V20.26';
const SRS_KEY='sproochentest-srs-v1', DONE_KEY='sproochentest-lessons-done-v1', RTL_KEY='sproochentest-rtl-vocab-v1';
let lessonVocab={}, timer=null, timerLeft=0, convIndex=0;
const conversations=[
 'Parle de ta famille et pose ensuite deux questions à ton interlocuteur.',
 'Explique une journée habituelle du matin au soir.',
 'Parle de ton travail ou de tes études et de ce que tu aimes ou non.',
 'Explique ce que tu fais pendant ton temps libre.',
 'Raconte ce que tu as fait le week-end dernier.',
 'Parle de tes prochaines vacances ou d’un projet proche.',
 'Explique comment tu fais tes courses et ce que tu achètes souvent.',
 'Parle de ton logement et de ton quartier.',
 'Explique comment tu te déplaces au quotidien.',
 'Parle d’un repas que tu aimes et de la façon dont tu le prépares.'
];
const css=document.createElement('style');css.textContent=`
#lesson{display:none!important}.spHero{background:linear-gradient(145deg,#fff,#eef7ff)}.spHero h2{margin:7px 0 8px;font-size:28px}.spGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.spTile{padding:15px;border:1px solid var(--line);border-radius:16px;background:#fff;text-align:left;box-shadow:var(--shadow)}.spTile b{display:block;font-size:16px;margin-bottom:4px}.spTile small{color:var(--muted);line-height:1.35}.spNum{font-size:28px;font-weight:950}.spRow{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.spRow input{width:95px;padding:11px;border:1px solid var(--line);border-radius:12px;font:inherit}.spBtn{padding:11px 13px;border-radius:12px;background:var(--blue2);color:#115c9f;font-weight:800}.spBtn.go{background:var(--blue);color:#fff}.spOverlay{position:fixed;inset:0;z-index:10000;background:var(--bg);overflow:auto;display:none}.spOverlay.open{display:block}.spWrap{max-width:720px;margin:auto;padding:16px 16px 90px}.spTop{display:flex;align-items:center;gap:10px;margin-bottom:14px}.spTop h2{margin:0;font-size:20px}.spBack{padding:10px 12px;border-radius:12px;background:#fff;border:1px solid var(--line);font-weight:800}.spPrompt{padding:15px;border-radius:14px;background:#f5f7fa;font-size:18px;font-weight:780;line-height:1.45;margin:10px 0}.spTimer{font-size:34px;text-align:center;font-weight:950;margin:11px 0}.spPhoto{width:100%;max-height:46vh;object-fit:contain;background:#111;border-radius:14px;margin-top:10px}.spChecklist{line-height:1.55;color:var(--muted)}.spReviewWord{font-size:32px;font-weight:950;text-align:center;margin:18px 0}.spAnswer{text-align:center;color:var(--muted);font-size:18px;margin:12px 0}.spRate{display:grid;grid-template-columns:repeat(3,1fr);gap:8px}.spRate button{padding:12px;border-radius:12px;font-weight:800}.spStatus{padding:10px 12px;background:#f4f6f9;border-radius:12px;color:var(--muted);font-size:13px;line-height:1.4;margin-top:9px}.spStep{padding:13px 0;border-bottom:1px solid var(--line)}.spStep:last-child{border-bottom:0}.spStep b{display:block;margin-bottom:4px}@media(max-width:430px){.spGrid{grid-template-columns:1fr}}
`;document.head.appendChild(css);
function jread(k,d){try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}}
function jwrite(k,v){localStorage.setItem(k,JSON.stringify(v))}
function norm(s){return String(s||'').trim().toLowerCase()}
function srs(){return jread(SRS_KEY,[])}
function addCard(lu,fr,source){if(!lu)return;const a=srs(),n=norm(lu),ex=a.find(x=>norm(x.lu)===n);if(ex){if(!ex.fr&&fr)ex.fr=fr;ex.sources=[...new Set([...(ex.sources||[ex.source]).filter(Boolean),source].filter(Boolean))];jwrite(SRS_KEY,a);return}a.push({lu,fr:fr||'',source,sources:[source],due:Date.now(),interval:0,reps:0});jwrite(SRS_KEY,a)}
function importRTL(){const a=jread(RTL_KEY,[]);a.forEach(x=>addCard(x.lu,x.fr&&x.fr!=='À réviser'?x.fr:'',x.source||'RTL'));}
async function loadLessonVocab(){try{const r=await fetch('./data/lesson-vocab.json?v=2',{cache:'no-store'});if(r.ok)lessonVocab=await r.json()}catch(e){};syncDoneLessons();renderDashboard()}
function syncDoneLessons(){const done=jread(DONE_KEY,[]);done.forEach(n=>(lessonVocab[String(n)]||[]).forEach(x=>addCard(x.lu,x.fr,'Leçon '+n)));importRTL()}
function dueCount(){const now=Date.now();return srs().filter(x=>(x.due||0)<=now).length}
function renderDashboard(){const home=document.getElementById('home');if(!home)return;const done=jread(DONE_KEY,[]),all=srs(),rtl=jread(RTL_KEY,[]);home.innerHTML=`
<div class="card spHero"><div class="eyebrow">Préparation Sproochentest</div><h2>Tout ce qui sert directement à l’examen.</h2><p class="muted">Le vocabulaire entre dans les révisions quand une leçon est terminée ou après une compréhension RTL. Le reste entraîne l’oral A2 et la compréhension B1.</p></div>
<div class="spGrid"><button class="spTile" id="goReview"><b>Réviser le vocabulaire</b><small><span class="spNum">${dueCount()}</span> carte(s) à revoir maintenant</small></button><button class="spTile" id="goJournal"><b>Compréhension RTL</b><small>${rtl.length} mot(s) déjà sélectionné(s) depuis les journaux</small></button><button class="spTile" id="goConv"><b>Conversations quotidiennes</b><small>Parler 5 minutes sur un sujet A2</small></button><button class="spTile" id="goImage"><b>Description d’images</b><small>Décrire et comparer pendant 5 minutes</small></button><button class="spTile" id="goExam"><b>Simulation d’examen</b><small>Oral 10 min + compréhension structurée</small></button></div>
<div class="card" style="margin-top:14px"><div class="eyebrow">Vocabulaire des leçons</div><h3 style="margin:6px 0 8px">Je viens de finir une leçon</h3><div class="spRow"><input id="lessonDoneNo" type="number" min="1" placeholder="N°"><button id="lessonDoneBtn" class="spBtn go">Leçon terminée</button></div><div id="lessonDoneStatus" class="spStatus">${done.length?done.length+' leçon(s) déjà signalée(s).':'Aucune leçon signalée pour l’instant.'}</div></div>
<div class="card"><div class="eyebrow">Principe</div><div class="spStep"><b>1. Leçon terminée</b><small>Son vocabulaire rejoint automatiquement la répétition espacée.</small></div><div class="spStep"><b>2. Journal RTL</b><small>Les mots utiles sélectionnés dans le journal rejoignent la même file, sans doublons.</small></div><div class="spStep"><b>3. Entraînement ciblé</b><small>Conversation, image et simulation reproduisent les compétences réellement évaluées.</small></div></div>`;
document.getElementById('goReview').onclick=()=>show('review');document.getElementById('goJournal').onclick=()=>show('news');document.getElementById('goConv').onclick=()=>openConv();document.getElementById('goImage').onclick=()=>openImage();document.getElementById('goExam').onclick=()=>openExam();document.getElementById('lessonDoneBtn').onclick=markLesson;
}
function markLesson(){const input=document.getElementById('lessonDoneNo'),n=Math.max(1,Number(input.value)||0),st=document.getElementById('lessonDoneStatus');if(!n)return;let done=jread(DONE_KEY,[]);if(!done.includes(n)){done.push(n);done.sort((a,b)=>a-b);jwrite(DONE_KEY,done)}const v=lessonVocab[String(n)]||[];v.forEach(x=>addCard(x.lu,x.fr,'Leçon '+n));if(st)st.innerHTML=v.length?`<strong>${v.length} élément(s) ajoutés.</strong> Ils sont maintenant dans Réviser.`:`Leçon ${n} mémorisée. Son vocabulaire sera ajouté automatiquement dès qu’il aura été importé dans l’application.`;renderDashboard()}
function renderSrs(){importRTL();const box=document.getElementById('reviewContent'),count=document.getElementById('reviewCount');if(!box)return;const now=Date.now(),a=srs(),due=a.filter(x=>(x.due||0)<=now).sort((x,y)=>(x.due||0)-(y.due||0));if(count)count.textContent=due.length+' à revoir';if(!due.length){box.innerHTML='<div class="notice">Rien à réviser maintenant. Les nouvelles cartes apparaissent après une leçon terminée ou depuis le vocabulaire RTL.</div>';return}const c=due[0],src=(c.sources||[c.source]).filter(Boolean).join(' · ');box.innerHTML=`<div class="tiny">${src}</div><div class="spReviewWord">${esc(c.lu)}</div><button class="primary" id="showAns">Voir la réponse</button><div id="ansArea" style="display:none"><div class="spAnswer">${esc(c.fr||'Traduction non encore renseignée')}</div><div class="spRate"><button data-r="1">Difficile</button><button data-r="2">Correct</button><button data-r="3">Facile</button></div></div>`;document.getElementById('showAns').onclick=()=>{document.getElementById('showAns').style.display='none';document.getElementById('ansArea').style.display='block'};box.querySelectorAll('[data-r]').forEach(b=>b.onclick=()=>rate(c,Number(b.dataset.r)))}
function rate(c,r){const a=srs(),x=a.find(z=>norm(z.lu)===norm(c.lu));if(!x)return;x.reps=(x.reps||0)+1;if(r===1)x.interval=1;else if(r===2)x.interval=Math.max(2,Math.round((x.interval||1)*2.2));else x.interval=Math.max(4,Math.round((x.interval||1)*3.5));x.due=Date.now()+x.interval*86400000;jwrite(SRS_KEY,a);renderSrs();renderDashboard()}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function overlay(id,title,body){let o=document.getElementById(id);if(!o){o=document.createElement('div');o.id=id;o.className='spOverlay';document.body.appendChild(o)}o.innerHTML=`<div class="spWrap"><div class="spTop"><button class="spBack">← Retour</button><h2>${title}</h2></div>${body}</div>`;o.classList.add('open');o.querySelector('.spBack').onclick=()=>closeOverlay(o);return o}
function closeOverlay(o){o.classList.remove('open');if(timer){clearInterval(timer);timer=null}}
function startTimer(el,seconds){if(timer)clearInterval(timer);timerLeft=seconds;const draw=()=>{el.textContent=String(Math.floor(timerLeft/60)).padStart(2,'0')+':'+String(timerLeft%60).padStart(2,'0')};draw();timer=setInterval(()=>{timerLeft--;draw();if(timerLeft<=0){clearInterval(timer);timer=null}},1000)}
function openConv(){const o=overlay('spConv','Conversation quotidienne',`<div class="card"><div class="eyebrow">Entretien A2</div><div class="spPrompt" id="convPrompt">${esc(conversations[convIndex])}</div><div class="spTimer" id="convTimer">05:00</div><div class="spRow"><button class="spBtn go" id="convStart">Démarrer 5 min</button><button class="spBtn" id="convNext">Autre sujet</button></div><p class="spChecklist">Réponds avec des phrases simples, puis ajoute des détails. Pense à interagir : répondre, préciser, demander quelque chose à ton interlocuteur.</p></div>`);o.querySelector('#convStart').onclick=()=>startTimer(o.querySelector('#convTimer'),300);o.querySelector('#convNext').onclick=()=>{convIndex=(convIndex+1)%conversations.length;o.querySelector('#convPrompt').textContent=conversations[convIndex]}}
function openImage(){const o=overlay('spImage','Description d’image',`<div class="card"><div class="eyebrow">Support visuel A2</div><input id="photoPick" type="file" accept="image/*"><img id="photoPreview" class="spPhoto" style="display:none"><div class="spTimer" id="imgTimer">05:00</div><div class="spRow"><button class="spBtn go" id="imgStart">Démarrer 5 min</button></div><p class="spChecklist"><b>À couvrir :</b> où se passe la scène, qui est présent, ce que les personnes font, objets/couleurs/positions, puis au moins une comparaison. Ne cherche pas des phrases compliquées : privilégie une description continue et compréhensible.</p></div>`);o.querySelector('#photoPick').onchange=e=>{const f=e.target.files?.[0],img=o.querySelector('#photoPreview');if(!f)return;img.src=URL.createObjectURL(f);img.style.display='block'};o.querySelector('#imgStart').onclick=()=>startTimer(o.querySelector('#imgTimer'),300)}
function openExam(){const o=overlay('spExam','Simulation Sproochentest',`<div class="card"><div class="eyebrow">Expression orale · 10 min</div><div class="spStep"><b>1. Entretien — 5 min</b><small>Choisis un des deux sujets : famille et vie quotidienne / travail et loisirs.</small></div><div class="spStep"><b>2. Support visuel — 5 min</b><small>Choisis une photo de ton téléphone, décris-la puis compare des personnes, objets ou activités.</small></div><div class="spTimer" id="examTimer">10:00</div><button class="spBtn go" id="examStart">Démarrer l’oral de 10 min</button></div><div class="card"><div class="eyebrow">Compréhension orale · B1</div><div class="spStep"><b>1. Message / information radio</b><small>Utilise un journal RTL et cherche uniquement l’essentiel.</small></div><div class="spStep"><b>2. Conversation quotidienne</b><small>Entraîne-toi à repérer qui parle, le problème, la décision et les informations pratiques.</small></div><div class="spStep"><b>3. Échange ou présentation</b><small>Repère le thème, les idées principales et quelques détails précis.</small></div><div class="spRow" style="margin-top:12px"><button class="spBtn go" id="examJournal">Ouvrir le Journal RTL</button></div><p class="spChecklist">L’épreuve officielle de compréhension comporte 3 textes et dure environ 35 minutes. Après chaque écoute, réponds sans revenir au texte.</p></div>`);o.querySelector('#examStart').onclick=()=>startTimer(o.querySelector('#examTimer'),600);o.querySelector('#examJournal').onclick=()=>{closeOverlay(o);show('news')}}
function enhanceRTL(){const box=document.getElementById('rtlVocab');if(!box||document.getElementById('rtlAddAll'))return;const b=document.createElement('button');b.id='rtlAddAll';b.className='spBtn go';b.textContent='Ajouter tous ces mots aux révisions';b.style.marginTop='10px';b.onclick=()=>{box.querySelectorAll('.rtlWord').forEach(w=>{const lu=w.dataset.w||w.textContent.trim();addCard(lu,'','RTL');w.classList.add('saved')});renderDashboard()};box.insertAdjacentElement('afterend',b)}
const oldRenderNews=window.renderNews;window.renderNews=function(){if(typeof oldRenderNews==='function')oldRenderNews();setTimeout(enhanceRTL,500)};
window.renderReview=renderSrs;
function init(){document.querySelectorAll('.brand small').forEach(x=>x.textContent=VERSION+' · entraînement ciblé');document.title='Sproochentest Lëtzebuergesch '+VERSION;const nav=document.querySelectorAll('.nav button');if(nav[0])nav[0].innerHTML='<span>⌂</span>Accueil';if(nav[1])nav[1].innerHTML='<span>↻</span>Réviser';if(nav[2])nav[2].innerHTML='<span>▶</span>Journal';document.getElementById('stModeCard')?.remove();renderDashboard();loadLessonVocab()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0));else setTimeout(init,0);
})();
