// V20.3 — réponses audio fiables + expression orale concrète
(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
.v203feedback{margin:10px 0 4px;padding:10px 12px;border-radius:11px;font-size:13px;font-weight:750}.v203feedback.ok{background:#e5f6ed;color:#17643d}.v203feedback.ko{background:#fde9eb;color:#9f2633}.v203task{font-size:24px;font-weight:900;line-height:1.2;margin:8px 0 12px}.v203say{padding:10px 0;border-bottom:1px solid var(--line)}.v203say b{display:block;font-size:14px}.v203say .fr{font-size:12px;color:var(--muted);margin:2px 0 5px}.v203say .lu{font-size:15px;font-weight:800}.v203record{margin:14px 0;padding:12px;border-radius:12px;background:#e8f3fd}.v203record b{display:block;margin-bottom:3px}.v203score{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:10px}.v203score button{padding:10px;border-radius:10px;font-weight:800;background:#e9eef3;color:var(--ink)}
`;document.head.appendChild(css);
function speakingPlan(i){const l=lessons[i],w=l.words.map(x=>x[0]);if(i===0)return{task:'Fais ce mini-dialogue à voix haute.',lines:[['Dis bonjour.','Moien!'],['Demande comment ça va.','Wéi geet et?'],['Prends congé.','Äddi! / Bis geschwënn!']]};if(i===3)return{task:'Présente-toi en suivant exactement ces 4 lignes.',lines:[['Je m’appelle …','Ech heeschen …'],['Je viens de …','Ech kommen aus …'],['J’habite à …','Ech wunnen zu …'],['Je parle …','Ech schwätzen …']]};if(i===8)return{task:'Présente ta famille en 4 phrases.',lines:[['Ma famille …','Meng Famill …'],['J’ai …','Ech hunn …'],['Ma mère / mon père …','Meng Mamm / Mäi Papp …'],['Ajoute un détail.','…']]};if(i===27)return{task:'Décris une image en 4 étapes.',lines:[['Ce que tu vois globalement.','Op dem Bild gesinn ech …'],['Une personne ou un objet.','Ech gesinn …'],['Ce qui se passe.','Hien / Si …'],['Où se trouve un élément.','virun / hannert / nieft …']]};return{task:`Parle de « ${l.title} » en 3 phrases.`,lines:[['Phrase 1 : donne l’information principale.',w[0]||'…'],['Phrase 2 : ajoute une information.',w[1]||'…'],['Phrase 3 : dis quelque chose de personnel.',w[2]||'…']]}}
function renderSpeaking203(){const p=speakingPlan(activeLesson);lessonContent.innerHTML=`<div class="v202stage">Expression orale · à toi de parler</div><div class="v203task">${p.task}</div>${p.lines.map((r,n)=>`<div class="v203say"><b>${n+1}. ${r[0]}</b><div class="fr">Repère</div><div class="lu">${r[1]}</div></div>`).join('')}<div class="v203record"><b>Maintenant : parle sans lire.</b><span class="v202mini">Fais toute la réponse d’une traite.</span></div><button class="primary" onclick="v203SelfEval()">J’ai fini de parler</button><div id="v202Eval"></div>`}
window.v202AnswerAudio=function(choice,btn){const x=listens[li];if(!x||!btn)return;const bs=btn.parentElement.querySelectorAll('.v202audioChoice');bs.forEach((b,i)=>{b.disabled=true;b.classList.remove('good','bad');if(i===x.a)b.classList.add('good')});if(choice!==x.a)btn.classList.add('bad');const reveal=document.getElementById('v202AudioReveal');if(!reveal)return;const last=li+1>=listens.length;reveal.innerHTML=`<div class="v203feedback ${choice===x.a?'ok':'ko'}">${choice===x.a?'✓ Bonne réponse':'✗ Réponse attendue : '+x.o[x.a]}</div><div class="v202trans"><button onclick="v202Toggle(this,'lu')">Afficher le luxembourgeois</button><div class="box" data-lang="lu"><div class="label">Luxembourgeois</div>${x.lu}</div><button onclick="v202Toggle(this,'fr')">Afficher le français</button><div class="box" data-lang="fr"><div class="label">Français</div>${x.fr}</div></div><button class="primary" style="margin-top:11px" id="v203next">${last?'Passer à l’expression orale':'Écoute suivante'}</button>`;document.getElementById('v203next').addEventListener('click',()=>{if(last)renderSpeaking203();else{li++;renderListening()}});reveal.scrollIntoView({behavior:'smooth',block:'nearest'})};
window.v202RestartSpeaking=renderSpeaking203;
window.v203SelfEval=function(){document.getElementById('v202Eval').innerHTML=`<div class="v202section">Comment ça s’est passé ?</div><div class="v203score"><button onclick="v203Rate(0)">Je n’y arrive pas</button><button onclick="v203Rate(1)">Avec beaucoup d’aide</button><button onclick="v203Rate(2)">Avec quelques hésitations</button><button onclick="v203Rate(3)">Sans aide</button></div>`};
window.v203Rate=function(n){if(n<2){document.getElementById('v202Eval').innerHTML=`<div class="v203feedback ko">À retravailler. Relis les repères, puis refais exactement le même exercice.</div><button class="primary" onclick="v202RestartSpeaking()">Refaire maintenant</button>`;return}if(!state.done.includes(activeLesson)){state.done.push(activeLesson);state.done.sort((a,b)=>a-b);save()}lessonContent.innerHTML=`<div class="v202summary" style="text-align:center"><div style="font-size:42px">✓</div><h2>Leçon validée</h2><p class="v202mini">Vocabulaire dans les deux sens + écoutes + réponse orale réalisée.</p><button class="primary" onclick="show('home')">Continuer le parcours</button></div>`};
document.querySelectorAll('.brand small').forEach(x=>x.textContent='V20.3 · préparation Sproochentest');
})();