// V20.24 — complément Assimil orienté Sproochentest
(function(){
'use strict';
const VERSION='V20.24', KEY='sproochentest-assimil-mode-v1';
const prompts=[
 {title:'Se présenter',q:'Présente-toi : nom, âge, lieu de vie, famille, travail et langues.'},
 {title:'Vie quotidienne',q:'Raconte une journée habituelle, du matin au soir.'},
 {title:'Loisirs',q:'Explique ce que tu aimes faire pendant ton temps libre et pourquoi.'},
 {title:'Projet',q:'Parle d’un projet pour les prochaines semaines ou les prochaines vacances.'},
 {title:'Décrire une image',q:'Choisis une photo courante. Dis qui est là, où ils sont, ce qu’ils font, puis compare deux éléments.'},
 {title:'Donner son avis',q:'Choisis un sujet simple et donne ton avis avec au moins deux raisons.'}
];
const css=document.createElement('style');css.textContent=`
.stModeCard{margin-top:14px;background:linear-gradient(145deg,#eef7ff,#fff);border:1px solid #d9eafa;border-radius:18px;padding:16px}.stModeCard h3{margin:4px 0 7px}.stModeCard p{margin:0 0 12px;color:var(--muted);line-height:1.4}.stModeOpen{width:100%;padding:13px;border-radius:13px;background:var(--blue);color:#fff;font-weight:850}
.stOverlay{position:fixed;inset:0;z-index:9999;background:var(--bg);overflow:auto;display:none}.stOverlay.open{display:block}.stWrap{max-width:720px;margin:auto;padding:16px 16px 90px}.stTop{display:flex;align-items:center;gap:10px;margin-bottom:13px}.stBack{padding:10px 12px;border-radius:12px;background:#fff;border:1px solid var(--line);font-weight:800}.stTop h2{margin:0;font-size:20px}.stBlock{background:#fff;border:1px solid var(--line);border-radius:18px;padding:16px;margin-bottom:12px;box-shadow:var(--shadow)}.stBlock h3{margin:0 0 8px}.stSmall{font-size:13px;color:var(--muted);line-height:1.4}.stGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.stTask{padding:12px;border-radius:13px;background:#f5f7fa;border:1px solid var(--line);text-align:left}.stTask.done{background:var(--green2);border-color:#a7dcc2}.stTask b{display:block;margin-bottom:3px}.stTask small{color:var(--muted)}.stBar{height:9px;border-radius:99px;background:#e8edf4;overflow:hidden;margin:10px 0}.stBar span{display:block;height:100%;background:var(--blue);width:0}.stButtons{display:flex;gap:8px;flex-wrap:wrap}.stButtons button{padding:10px 12px;border-radius:12px;background:var(--blue2);color:#115c9f;font-weight:800}.stButtons .go{background:var(--blue);color:#fff}.stPrompt{padding:14px;border-radius:14px;background:#f6f8fb;font-size:17px;font-weight:750;line-height:1.4;margin:10px 0}.stTimer{font-size:32px;font-weight:950;text-align:center;margin:10px 0}.stLesson{display:flex;align-items:center;gap:9px}.stLesson input{width:90px;padding:10px;border:1px solid var(--line);border-radius:11px;font:inherit}.stScore{font-size:12px;color:var(--muted);margin-top:8px}@media(max-width:420px){.stGrid{grid-template-columns:1fr}}
`;document.head.appendChild(css);
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function today(){return new Date().toISOString().slice(0,10)}
function state(){const s=load();if(s.day!==today())return{day:today(),tasks:{},lesson:s.lesson||1,totalDays:s.totalDays||0};return s}
function ensureCard(){const home=document.getElementById('home');if(!home||document.getElementById('stModeCard'))return;const card=document.createElement('div');card.id='stModeCard';card.className='stModeCard';card.innerHTML='<div class="eyebrow">Complément Assimil</div><h3>Mode Sproochentest</h3><p>Assimil pour construire la langue. Ici : expression orale A2, compréhension réelle, automatisation et simulations ciblées.</p><button class="stModeOpen">Entraînement du jour</button>';home.appendChild(card);card.querySelector('button').onclick=openMode}
let timer=null,left=0,currentPrompt=0;
function openMode(){let o=document.getElementById('stOverlay');if(!o){o=document.createElement('div');o.id='stOverlay';o.className='stOverlay';document.body.appendChild(o)}o.classList.add('open');renderMode()}
function closeMode(){document.getElementById('stOverlay')?.classList.remove('open');if(timer){clearInterval(timer);timer=null}}
function pct(s){const n=['assimil','shadow','oral','listen','review'].filter(k=>s.tasks?.[k]).length;return Math.round(n/5*100)}
function renderMode(){const s=state(),o=document.getElementById('stOverlay');if(!o)return;const p=pct(s);o.innerHTML=`<div class="stWrap"><div class="stTop"><button class="stBack">← Retour</button><div><h2>Entraînement Sproochentest</h2><div class="stSmall">Routine courte, directement complémentaire d’Assimil</div></div></div>
<div class="stBlock"><h3>Aujourd’hui</h3><div class="stBar"><span style="width:${p}%"></span></div><div class="stSmall">${p}% de la routine ciblée terminée.</div><div class="stGrid" style="margin-top:10px">
${task('assimil','Assimil','20–30 min · leçon + audio',s)}${task('shadow','Répétition à voix haute','10 min · imiter l’audio Assimil',s)}${task('oral','Oral spontané','10 min · sans lire',s)}${task('listen','Compréhension','15 min · RTL ou dialogue',s)}${task('review','Révisions','10 min · cartes difficiles',s)}</div></div>
<div class="stBlock"><h3>Suivi Assimil</h3><div class="stLesson"><span>Leçon actuelle</span><input id="stLesson" type="number" min="1" max="200" value="${Number(s.lesson)||1}"><button class="secondary" id="stLessonSave">Enregistrer</button></div><p class="stSmall">But : écouter plusieurs fois, répéter à voix haute puis réutiliser 2–3 phrases sans regarder le livre.</p></div>
<div class="stBlock"><h3>Expression orale A2</h3><div class="stPrompt"><b>${prompts[currentPrompt].title}</b><br>${prompts[currentPrompt].q}</div><div class="stTimer" id="stTimer">02:00</div><div class="stButtons"><button class="go" id="stStart">Démarrer 2 min</button><button id="stNew">Autre sujet</button><button id="stOralDone">✓ Fait</button></div><div class="stScore">Règle : phrases simples mais continues. Évite de traduire mentalement mot à mot.</div></div>
<div class="stBlock"><h3>Compréhension B1</h3><p class="stSmall">Prends un journal RTL préparé. 1re écoute : regarde surtout l’image et écoute. 2e : utilise le luxembourgeois sous la vidéo. 3e : vérifie avec le français RTL. Ensuite résume à voix haute en 3 phrases simples.</p><div class="stButtons"><button class="go" id="stGoJournal">Ouvrir Journal</button><button id="stListenDone">✓ Compréhension faite</button></div></div>
<div class="stBlock"><h3>Objectif avant l’examen</h3><div class="stSmall">Tu es prêt quand tu peux parler plusieurs minutes sur des sujets quotidiens sans texte préparé, décrire/comparer une image et comprendre régulièrement l’essentiel des audios d’actualité et de conversation. L’application doit servir à automatiser ces compétences, pas à remplacer Assimil.</div></div></div>`;
o.querySelector('.stBack').onclick=closeMode;o.querySelectorAll('.stTask').forEach(b=>b.onclick=()=>toggle(b.dataset.k));
document.getElementById('stLessonSave').onclick=()=>{const x=Math.max(1,Number(document.getElementById('stLesson').value)||1),q=state();q.lesson=x;save(q);renderMode()};
document.getElementById('stStart').onclick=startTimer;document.getElementById('stNew').onclick=()=>{currentPrompt=(currentPrompt+1)%prompts.length;renderMode()};document.getElementById('stOralDone').onclick=()=>mark('oral');document.getElementById('stListenDone').onclick=()=>mark('listen');document.getElementById('stGoJournal').onclick=()=>{closeMode();const btn=[...document.querySelectorAll('.nav button')].find(b=>/journal|rtl|news/i.test(b.textContent));if(btn)btn.click();else document.getElementById('news')?.classList.add('active')};}
function task(k,t,d,s){return `<button class="stTask ${s.tasks?.[k]?'done':''}" data-k="${k}"><b>${s.tasks?.[k]?'✓ ':''}${t}</b><small>${d}</small></button>`}
function toggle(k){const s=state();s.tasks=s.tasks||{};s.tasks[k]=!s.tasks[k];save(s);renderMode()}
function mark(k){const s=state();s.tasks=s.tasks||{};s.tasks[k]=true;save(s);renderMode()}
function startTimer(){if(timer)clearInterval(timer);left=120;const e=document.getElementById('stTimer');const draw=()=>{if(e)e.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0')};draw();timer=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timer);timer=null;mark('oral')}},1000)}
const mo=new MutationObserver(ensureCard);mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureCard);else ensureCard();
document.querySelectorAll('.brand small').forEach(x=>x.textContent=VERSION+' · Assimil + Sproochentest');document.title='Sproochentest Lëtzebuergesch '+VERSION;
})();