// V20.8 — expression orale A2 progressive et simulation
(function(){
'use strict';
const css=document.createElement('style');css.textContent=`
.v208level{padding:13px 0;border-bottom:1px solid var(--line)}.v208level b{display:block;font-size:15px}.v208level small{display:block;color:var(--muted);line-height:1.4;margin:4px 0 9px}.v208level button,.v208btn{padding:9px 11px;border-radius:10px;background:var(--blue2);color:var(--blue);font-weight:850}.v208card{padding:14px 0;border-bottom:1px solid var(--line)}.v208q{font-size:20px;font-weight:900;line-height:1.3;margin:7px 0}.v208help{padding:11px;border-radius:11px;background:#e9eef3;line-height:1.45;margin:9px 0}.v208help em{color:var(--muted)}.v208answer{display:none;padding:11px;border-radius:11px;background:var(--green2);line-height:1.5;margin:8px 0}.v208checks label{display:block;padding:7px 0}.v208timer{font-size:38px;font-weight:950;margin:8px 0}.v208scene{padding:14px;border-radius:14px;background:#e9eef3;font-size:42px;text-align:center;margin:10px 0}.v208score{font-size:32px;font-weight:950;margin:7px 0}
`;document.head.appendChild(css);
let screen=document.getElementById('speakingLab');if(!screen){screen=document.createElement('section');screen.id='speakingLab';screen.className='screen';screen.innerHTML='<button class="back" onclick="show(\'examPrep\')">← Retour</button><div id="speakingLabContent"></div>';document.querySelector('.app').appendChild(screen)}
const qs=[
['Wéi heeschs du a wou wunns du?','Je m’appelle… / J’habite à…','Ech heeschen Anna an ech wunnen zu Thionville.'],
['Wat méchs du gär an denger Fräizäit?','J’aime… / Pendant mon temps libre…','A menger Fräizäit ginn ech gär spadséieren an ech lauschtere Musek.'],
['Erziel mer e bëssen iwwer deng Famill.','Dans ma famille… / J’ai…','Ech si bestuet. Meng Famill ass net ganz grouss a mir gesinn eis dacks.'],
['Wéi gesäit en normalen Dag bei dir aus?','Le matin… ensuite… le soir…','Moies stinn ech op a ginn op d’Aarbecht. Owes iessen ech doheem a raschten.'],
['Wat hues du de leschte Weekend gemaach?','Le week-end dernier… puis…','De leschte Weekend war ech an der Stad. Duerno hunn ech doheem giess.'],
['Wat wëlls du nächst Weekend maachen?','Je voudrais… / je vais…','Nächst Weekend wëll ech Frënn gesinn an e bëssen erausgoen.']
];
const scenes=[
['🚌🏙️👩','Bus en ville','Beschreif d’Situatioun. Wou ass d’Persoun? Wat mécht si? Wou kéint si hifueren?','Ech gesinn eng Fra bei engem Bus an der Stad. Si waart wahrscheinlech op de Bus. Vläicht fiert si op d’Aarbecht.'],
['🛒🥖🍎','Courses','Wat gesäis du? Wat mécht d’Persoun? Wat keeft si?','D’Persoun ass an engem Geschäft. Si keeft Brout an Äppel. Si mécht hir Akeef.'],
['☕👥🌤️','Café','Beschreif d’Bild a sot, wat d’Leit maachen.','Ech gesinn Leit an engem Café. Si sëtzen zesummen, drénke Kaffi a schwätzen. D’Wieder ass gutt.']
];
let qi=0,mode=0,timer=null,seconds=0;
window.openSpeakingLab=function(){clearInterval(timer);document.getElementById('speakingLabContent').innerHTML=`<div class="v204stage">Expression orale A2</div><h2 style="margin:4px 0 8px">Parler progressivement sans aide</h2><p class="muted">Le but n’est pas de réciter parfaitement : répondre simplement, développer avec 2–4 phrases et rester compréhensible.</p><div class="v208level"><b>1 · Très guidé</b><small>Question + amorces + exemple. À utiliser pour apprendre les structures.</small><button onclick="v208Start(0)">Commencer</button></div><div class="v208level"><b>2 · Aide réduite</b><small>Question + quelques mots d’appui. L’exemple n’apparaît qu’après la réponse.</small><button onclick="v208Start(1)">Commencer</button></div><div class="v208level"><b>3 · Entretien autonome</b><small>Questions d’examinateur sans aide. Auto-évaluation après chaque réponse.</small><button onclick="v208Start(2)">Commencer</button></div><div class="v208level"><b>4 · Décrire une situation</b><small>Support visuel symbolique : décrire qui, où, quoi et ajouter une hypothèse simple.</small><button onclick="v208Scenes()">Commencer</button></div><div class="v208level"><b>5 · Simulation chronométrée</b><small>Enchaînement autonome : présentation, questions et description, avec temps visible.</small><button onclick="v208Simulation()">Lancer la simulation</button></div>`;show('speakingLab')};
window.v208Start=function(m){mode=m;qi=0;renderQ()};
function renderQ(){if(qi>=qs.length){document.getElementById('speakingLabContent').innerHTML='<div class="v204stage">Terminé</div><h2>Entretien terminé</h2><p class="muted">Refais ce niveau jusqu’à pouvoir répondre immédiatement en 2 à 4 phrases simples.</p><button class="primary" onclick="openSpeakingLab()">Retour aux niveaux</button>';return}const q=qs[qi];const hint=mode===0?`<div class="v208help"><b>Amorces</b><br>${q[1]}<br><br><em>Exemple : ${q[2]}</em></div>`:mode===1?`<div class="v208help"><b>Mots d’appui</b><br>${q[1]}</div>`:'';document.getElementById('speakingLabContent').innerHTML=`<div class="v204stage">Entretien · ${qi+1}/${qs.length}</div><div class="v208card"><div class="v208q">${q[0]}</div>${hint}<p><b>Réponds maintenant à voix haute.</b> Essaie de faire au moins 2 phrases.</p><button class="v208btn" onclick="v208Reveal()">J’ai répondu · m’évaluer</button><div class="v208answer" id="v208answer"><b>Exemple possible</b><br>${q[2]}</div><div id="v208self"></div></div>`}
window.v208Reveal=function(){document.getElementById('v208answer').style.display='block';document.getElementById('v208self').innerHTML=`<div class="v208checks"><label><input type="checkbox"> J’ai répondu à la question.</label><label><input type="checkbox"> J’ai fait au moins 2 phrases.</label><label><input type="checkbox"> J’ai parlé sans longue pause.</label><label><input type="checkbox"> Mon message serait compréhensible malgré quelques erreurs.</label></div><button class="primary" onclick="v208Next()">Question suivante</button>`};
window.v208Next=function(){qi++;renderQ()};
window.v208Scenes=function(){qi=0;renderScene()};
function renderScene(){if(qi>=scenes.length){openSpeakingLab();return}const s=scenes[qi];document.getElementById('speakingLabContent').innerHTML=`<div class="v204stage">Description · ${qi+1}/${scenes.length}</div><div class="v208scene" aria-label="${s[1]}">${s[0]}</div><div class="v208q">${s[2]}</div><div class="v208help"><b>Plan utile</b><br>1. Ech gesinn… &nbsp; 2. D’Persoun ass… &nbsp; 3. Si/Hie mécht… &nbsp; 4. Vläicht…</div><button class="v208btn" onclick="document.getElementById('v208sceneans').style.display='block'">Voir un exemple après avoir parlé</button><div class="v208answer" id="v208sceneans"><b>Exemple</b><br>${s[3]}<br><br><button class="primary" onclick="qi++;renderScene()">Situation suivante</button></div>`}
window.v208Simulation=function(){qi=0;seconds=0;clearInterval(timer);document.getElementById('speakingLabContent').innerHTML=`<div class="v204stage">Simulation A2</div><h2>Prête ?</h2><p class="muted">Parle sans lire d’exemple. La simulation enchaîne 4 questions puis une description.</p><button class="primary" onclick="v208SimGo()">Démarrer</button>`};
window.v208SimGo=function(){seconds=0;timer=setInterval(()=>{seconds++;const e=document.getElementById('v208time');if(e)e.textContent=Math.floor(seconds/60)+':'+String(seconds%60).padStart(2,'0')},1000);qi=0;renderSim()};
function renderSim(){if(qi>=5){clearInterval(timer);document.getElementById('speakingLabContent').innerHTML=`<div class="v204stage">Simulation terminée</div><div class="v208score">${Math.floor(seconds/60)} min ${seconds%60} s</div><p class="muted">Objectif : réponses simples, développées et compréhensibles, sans dépendre d’un texte préparé.</p><div class="v208checks"><label><input type="checkbox"> J’ai répondu à toutes les consignes.</label><label><input type="checkbox"> J’ai généralement produit plusieurs phrases.</label><label><input type="checkbox"> J’ai pu continuer même quand un mot me manquait.</label><label><input type="checkbox"> Je peux refaire la simulation avec moins d’hésitations.</label></div><button class="primary" onclick="openSpeakingLab()">Retour</button>`;return}let body;if(qi<4){body=`<div class="v208q">${qs[qi][0]}</div><p>Réponds à voix haute, sans aide.</p>`}else{const s=scenes[Math.floor(Math.random()*scenes.length)];body=`<div class="v208scene">${s[0]}</div><div class="v208q">${s[2]}</div>`}document.getElementById('speakingLabContent').innerHTML=`<div class="v204stage">Simulation · étape ${qi+1}/5</div><div class="v208timer" id="v208time">${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}</div>${body}<button class="primary" onclick="qi++;renderSim()">Réponse terminée · continuer</button>`}
const oldExam=window.openExamPrep;window.openExamPrep=function(){oldExam();setTimeout(()=>{const h=document.getElementById('examContent');if(!h)return;const rows=h.querySelectorAll('.v204examRow');rows.forEach(r=>{const b=r.querySelector('b');if(b&&(b.textContent.includes('Expression')||b.textContent.includes('orale'))){const bt=r.querySelector('button');if(bt){bt.textContent='Progression A2';bt.onclick=openSpeakingLab}const sm=r.querySelector('small');if(sm)sm.textContent='Très guidé → aide réduite → entretien autonome → description → simulation chronométrée.'}})},0)};
document.querySelectorAll('.brand small').forEach(x=>x.textContent='V20.8 · oral A2 + compréhension B1');document.title='Sproochentest Lëtzebuergesch V20.8';
})();