// V20.25 — complément spécifiquement Sproochentest
(function(){
'use strict';
const VERSION='V20.25', KEY='sproochentest-training-mode-v2';
const prompts=[
 {title:'Se présenter',q:'Présente-toi : nom, âge, lieu de vie, famille, travail et langues.'},
 {title:'Vie quotidienne',q:'Raconte une journée habituelle, du matin au soir.'},
 {title:'Loisirs',q:'Explique ce que tu aimes faire pendant ton temps libre et pourquoi.'},
 {title:'Projet',q:'Parle d’un projet pour les prochaines semaines ou les prochaines vacances.'},
 {title:'Décrire une image',q:'Choisis une photo courante. Dis qui est là, où ils sont, ce qu’ils font, puis compare deux éléments.'},
 {title:'Donner son avis',q:'Choisis un sujet simple et donne ton avis avec au moins deux raisons.'}
];
const css=document.createElement('style');css.textContent=`
.stModeCard{margin-top:14px;background:linear-gradient(145deg,#eef7ff,#fff);border:1px solid #d9eafa;border-radius:18px;padding:16px}.stModeCard h3{margin:4px 0 7px}.stModeCard p{margin:0 0 12px;color:var(--muted);line-height:1.4}.stModeOpen{width:100%;padding:13px;border-radius:13px;background:var(--blue);color:#fff;font-weight:850}
.stOverlay{position:fixed;inset:0;z-index:9999;background:var(--bg);overflow:auto;display:none}.stOverlay.open{display:block}.stWrap{max-width:720px;margin:auto;padding:16px 16px 90px}.stTop{display:flex;align-items:center;gap:10px;margin-bottom:13px}.stBack{padding:10px 12px;border-radius:12px;background:#fff;border:1px solid var(--line);font-weight:800}.stTop h2{margin:0;font-size:20px}.stBlock{background:#fff;border:1px solid var(--line);border-radius:18px;padding:16px;margin-bottom:12px;box-shadow:var(--shadow)}.stBlock h3{margin:0 0 8px}.stSmall{font-size:13px;color:var(--muted);line-height:1.4}.stGrid{display:grid;grid-template-columns:1fr 1fr;gap:9px}.stTask{padding:12px;border-radius:13px;background:#f5f7fa;border:1px solid var(--line);text-align:left}.stTask.done{background:var(--green2);border-color:#a7dcc2}.stTask b{display:block;margin-bottom:3px}.stTask small{color:var(--muted)}.stBar{height:9px;border-radius:99px;background:#e8edf4;overflow:hidden;margin:10px 0}.stBar span{display:block;height:100%;background:var(--blue);width:0}.stButtons{display:flex;gap:8px;flex-wrap:wrap}.stButtons button{padding:10px 12px;border-radius:12px;background:var(--blue2);color:#115c9f;font-weight:800}.stButtons .go{background:var(--blue);color:#fff}.stPrompt{padding:14px;border-radius:14px;background:#f6f8fb;font-size:17px;font-weight:750;line-height:1.4;margin:10px 0}.stTimer{font-size:32px;font-weight:950;text-align:center;margin:10px 0}.stScore{font-size:12px;color:var(--muted);margin-top:8px}@media(max-width:420px){.stGrid{grid-template-columns:1fr}}
`;document.head.appendChild(css);
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch(e){return{}}}
function save(s){localStorage.setItem(KEY,JSON.stringify(s))}
function today(){return new Date().toISOString().slice(0,10)}
function state(){const s=load();if(s.day!==today())return{day:today(),tasks:{},totalDays:s.totalDays||0};return s}
function ensureCard(){const home=document.getElementById('home');if(!home||document.getElementById('stModeCard'))return;const card=document.createElement('div');card.id='stModeCard';card.className='stModeCard';card.innerHTML='<div class="eyebrow">Préparation ciblée</div><h3>Mode Sproochentest</h3><p>Révisions espacées, compréhension réelle, conversations quotidiennes, descriptions d’images et simulations complètes.</p><button class="stModeOpen">Entraînement du jour</button>';home.appendChild(card);card.querySelector('button').onclick=openMode}
let timer=null,left=0,currentPrompt=0;
function openMode(){let o=document.getElementById('stOverlay');if(!o){o=document.createElement('div');o.id='stOverlay';o.className='stOverlay';document.body.appendChild(o)}o.classList.add('open');renderMode()}
function closeMode(){document.getElementById('stOverlay')?.classList.remove('open');if(timer){clearInterval(timer);timer=null}}
function pct(s){const n=['review','listen','dialogue','image','mock'].filter(k=>s.tasks?.[k]).length;return Math.round(n/5*100)}
function renderMode(){const s=state(),o=document.getElementById('stOverlay');if(!o)return;const p=pct(s);o.innerHTML=`<div class="stWrap"><div class="stTop"><button class="stBack">← Retour</button><div><h2>Entraînement Sproochentest</h2><div class="stSmall">Travail ciblé sur les compétences de l’examen</div></div></div>
<div class="stBlock"><h3>Aujourd’hui</h3><div class="stBar"><span style="width:${p}%"></span></div><div class="stSmall">${p}% de la routine ciblée terminée.</div><div class="stGrid" style="margin-top:10px">
${task('review','Révisions espacées','10 min · vocabulaire difficile',s)}${task('listen','Compréhension RTL','15 min · journal réel',s)}${task('dialogue','Conversation quotidienne','10 min · répondre spontanément',s)}${task('image','Description d’image','10 min · décrire et comparer',s)}${task('mock','Simulation examen','1 épreuve complète ou partielle',s)}</div></div>
<div class="stBlock"><h3>Expression orale A2</h3><div class="stPrompt"><b>${prompts[currentPrompt].title}</b><br>${prompts[currentPrompt].q}</div><div class="stTimer" id="stTimer">02:00</div><div class="stButtons"><button class="go" id="stStart">Démarrer 2 min</button><button id="stNew">Autre sujet</button><button id="stDialogueDone">✓ Conversation faite</button><button id="stImageDone">✓ Image faite</button></div><div class="stScore">Objectif : phrases simples, compréhensibles et continues, sans texte préparé.</div></div>
<div class="stBlock"><h3>Compréhension B1</h3><p class="stSmall">Utilise un journal RTL préparé. 1re écoute sans aide. 2e avec le luxembourgeois sous la vidéo. 3e vérifie avec le français RTL. Résume ensuite l’essentiel en 3 phrases simples.</p><div class="stButtons"><button class="go" id="stGoJournal">Ouvrir Journal</button><button id="stListenDone">✓ Compréhension faite</button></div></div>
<div class="stBlock"><h3>Simulation de l’examen</h3><p class="stSmall">Enchaîne sans interruption : compréhension d’un extrait, conversation quotidienne, puis description/comparaison d’une image. Note ce qui bloque et renvoie les mots ou expressions difficiles vers les révisions.</p><div class="stButtons"><button id="stMockDone" class="go">✓ Simulation faite</button></div></div>
<div class="stBlock"><h3>Objectif</h3><div class="stSmall">L’application sert uniquement à automatiser les compétences utiles au Sproochentest : vocabulaire actif, compréhension réelle, conversation, description d’image et entraînement en conditions d’examen.</div></div></div>`;
o.querySelector('.stBack').onclick=closeMode;o.querySelectorAll('.stTask').forEach(b=>b.onclick=()=>toggle(b.dataset.k));
document.getElementById('stStart').onclick=startTimer;document.getElementById('stNew').onclick=()=>{currentPrompt=(currentPrompt+1)%prompts.length;renderMode()};document.getElementById('stDialogueDone').onclick=()=>mark('dialogue');document.getElementById('stImageDone').onclick=()=>mark('image');document.getElementById('stListenDone').onclick=()=>mark('listen');document.getElementById('stMockDone').onclick=()=>mark('mock');document.getElementById('stGoJournal').onclick=()=>{closeMode();const btn=[...document.querySelectorAll('.nav button')].find(b=>/journal|rtl|news/i.test(b.textContent));if(btn)btn.click();else document.getElementById('news')?.classList.add('active')};}
function task(k,t,d,s){return `<button class="stTask ${s.tasks?.[k]?'done':''}" data-k="${k}"><b>${s.tasks?.[k]?'✓ ':''}${t}</b><small>${d}</small></button>`}
function toggle(k){const s=state();s.tasks=s.tasks||{};s.tasks[k]=!s.tasks[k];save(s);renderMode()}
function mark(k){const s=state();s.tasks=s.tasks||{};s.tasks[k]=true;save(s);renderMode()}
function startTimer(){if(timer)clearInterval(timer);left=120;const e=document.getElementById('stTimer');const draw=()=>{if(e)e.textContent=String(Math.floor(left/60)).padStart(2,'0')+':'+String(left%60).padStart(2,'0')};draw();timer=setInterval(()=>{left--;draw();if(left<=0){clearInterval(timer);timer=null;mark('dialogue')}},1000)}
const mo=new MutationObserver(ensureCard);mo.observe(document.documentElement,{childList:true,subtree:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureCard);else ensureCard();
document.querySelectorAll('.brand small').forEach(x=>x.textContent=VERSION+' · préparation Sproochentest');document.title='Sproochentest Lëtzebuergesch '+VERSION;
})();