// V20.4 — flux autonome + tuteur vocal + préparation examen
(function(){
'use strict';

const css=document.createElement('style');
css.textContent=`
.v204modes{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:10px 0 18px}.v204modes button{padding:11px 8px;border-radius:12px;background:#e9eef4;color:var(--ink);font-weight:800;font-size:12px}.v204modes span{display:block;font-size:20px;margin-bottom:3px}.v204stage{font-size:11px;font-weight:900;color:var(--blue);text-transform:uppercase;letter-spacing:.55px;margin-bottom:6px}.v204prompt{font-size:24px;font-weight:900;line-height:1.2;margin:14px 0}.v204counter{font-size:11px;color:var(--muted)}.v204reveal{display:inline-block;width:auto;padding:8px 12px;border-radius:10px;background:#e7edf4;color:#31506b;font-size:12px;font-weight:800}.v204answer{font-size:21px;font-weight:900;margin:12px 0 8px}.v204judge{display:flex;gap:8px}.v204judge button{flex:1;padding:10px;border-radius:10px;font-weight:800}.v204judge .bad{background:var(--red2);color:var(--red)}.v204judge .good{background:var(--green2);color:var(--green)}.v204choice{display:block;width:100%;text-align:left;padding:11px;border-radius:11px;background:#e9eef3;border:1px solid var(--line);margin:7px 0}.v204choice.good{background:var(--green2);border-color:#9cdbbd}.v204choice.bad{background:var(--red2);border-color:#f2adb4}.v204feedback{margin:10px 0;padding:10px 12px;border-radius:10px;font-size:13px;font-weight:800}.v204feedback.ok{background:#e5f6ed;color:#17643d}.v204feedback.ko{background:#fde9eb;color:#9f2633}.v204trans button{width:100%;padding:9px 11px;border-radius:10px;background:#e7edf4;color:#31506b;font-weight:800;margin-top:7px}.v204trans .box{display:none;padding:10px 11px;border-radius:10px;background:#e9eef3;margin-top:5px;line-height:1.4}.v204task{font-size:23px;font-weight:900;line-height:1.2;margin:8px 0 12px}.v204line{padding:10px 0;border-bottom:1px solid var(--line)}.v204line b{display:block;font-size:13px}.v204line .lu{font-weight:850;margin-top:4px}.v204self{display:grid;grid-template-columns:1fr 1fr;gap:7px;margin-top:12px}.v204self button{padding:10px;border-radius:10px;background:#e9eef3;font-weight:800}.v204tutor{padding:6px 0}.v204bubble{padding:12px 14px;border-radius:16px;background:#e8f3fd;margin:8px 0;line-height:1.4}.v204heard{padding:10px 12px;border-left:3px solid var(--blue);margin:10px 0;background:#eef3f8}.v204mic{width:100%;padding:14px;border-radius:13px;background:var(--blue);color:white;font-weight:900}.v204hint{margin-top:8px;font-size:12px;color:var(--muted)}.v204examRow{padding:13px 0;border-bottom:1px solid var(--line)}.v204examRow b{display:block}.v204examRow small{display:block;color:var(--muted);margin:3px 0 8px;line-height:1.35}.v204examRow button{padding:9px 11px;border-radius:10px;background:#e8f3fd;color:#145f9f;font-weight:800}
`;
document.head.appendChild(css);

function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function cardsForLesson(){const p=[];lessons[activeLesson].words.forEach((w,id)=>{p.push({id,dir:'Français → luxembourgeois',q:w[1],a:w[0]});p.push({id,dir:'Luxembourgeois → français',q:w[0],a:w[1]})});shuffle(p);const out=[];while(p.length){const prev=out[out.length-1];let c=p.map((x,i)=>({x,i})).filter(y=>!prev||y.x.id!==prev.id);if(!c.length)c=p.map((x,i)=>({x,i}));out.push(p.splice(c[Math.floor(Math.random()*c.length)].i,1)[0])}return out}

const audios=[
 {u:'https://lod.lu/uploads/examples/OGG/9b/9bb3ff56b0168aa51fe1737239761208.ogg',lu:'moien, Madamm, wat kann ech fir Iech maachen?',fr:'Bonjour Madame, que puis-je faire pour vous ?',q:'Que fait la personne ?',o:['Elle salue et propose son aide.','Elle dit au revoir.','Elle demande l’heure.'],a:0,t:'greeting'},
 {u:'https://lod.lu/uploads/examples/OGG/f2/f20e0cdaccb6c76c06f8720ac34ac7a9.ogg',lu:'moien, wéi geet et?',fr:'Bonjour, comment ça va ?',q:'Que demande la personne ?',o:['Comment ça va ?','Où habites-tu ?','Quel âge as-tu ?'],a:0,t:'greeting'},
 {u:'https://lod.lu/uploads/examples/OGG/92/926b1dbd7e2c5081e03a3a1a229605d8.ogg',lu:'salut, ech ginn elo heem!',fr:'Salut, je rentre maintenant à la maison !',q:'Que va faire la personne ?',o:['Elle rentre chez elle.','Elle va travailler.','Elle va au restaurant.'],a:0,t:'greeting'},
 {u:'https://lod.lu/uploads/examples/OGG/57/5708aa802f9771f2a431a9310f609b90.ogg',lu:'ech wunnen zu Eech',fr:'J’habite à Eich.',q:'Que dit la personne ?',o:['Elle habite à Eech.','Elle travaille à Eech.','Elle vient d’Eech.'],a:0,t:'present'},
 {u:'https://lod.lu/uploads/examples/OGG/99/993dc701e65f000216eed16a3d7b4dc0.ogg',lu:'déi nei Buslinn fiert vun der Gare op de Flughafen',fr:'La nouvelle ligne de bus va de la gare à l’aéroport.',q:'Quel trajet est annoncé ?',o:['De la gare à l’aéroport.','De l’aéroport au magasin.','De l’école à la gare.'],a:0,t:'transport'},
 {u:'https://lod.lu/uploads/examples/OGG/bd/bd64bfea677c6f9acc314b9fd4ed0cb2.ogg',lu:'mir hunn eng Taass Kaffi gedronk',fr:'Nous avons bu une tasse de café.',q:'Qu’ont-ils bu ?',o:['Une tasse de café.','Un verre d’eau.','Du thé.'],a:0,t:'food'},
 {u:'https://lod.lu/uploads/examples/OGG/4c/4c4f9a38005924e30b5af0572dc95d29.ogg',lu:'hien drénkt nëmme schwaarze Kaffi',fr:'Il boit uniquement du café noir.',q:'Quel café boit-il ?',o:['Du café noir.','Du café au lait.','Aucun café.'],a:0,t:'food'},
 {u:'https://lod.lu/uploads/examples/OGG/32/326d946b134d79ed507e0984cef18ad4.ogg',lu:"maach de Radio méi haart, ech wëll d'Wieder lauschteren!",fr:'Monte la radio, je veux écouter la météo !',q:'Pourquoi faut-il monter le volume ?',o:['Pour écouter la météo.','Pour téléphoner.','Pour écouter un match.'],a:0,t:'weather'},
 {u:'https://lod.lu/uploads/examples/OGG/5e/5e89147416f5f194d1231df26ec7d19c.ogg',lu:'am Autobus sinn nach Sëtzplaze fräi',fr:'Il reste des places assises libres dans le bus.',q:'Quelle information est donnée ?',o:['Il reste des places.','Le bus est complet.','Le bus est supprimé.'],a:0,t:'transport'}
];
function audioSet(i){if(typeof window.v213BuildListening==='function')return window.v213BuildListening(i).map(x=>({speech:x.speech,lu:x.lu,fr:x.fr,q:x.q,o:x.opts,a:x.a}));const title=(lessons[i].title||'').toLowerCase();let tags=['present'];if(i===0||title.includes('bonjour'))tags=['greeting'];else if(title.includes('transport')||title.includes('déplacement'))tags=['transport'];else if(title.includes('nourrit')||title.includes('café'))tags=['food'];else if(title.includes('météo'))tags=['weather'];let pool=audios.filter(x=>tags.includes(x.t));if(pool.length<3)pool=[...pool,...audios.filter(x=>!pool.includes(x))];return pool.slice(0,3)}

let phaseCards=[],pos=0,good=0,shown=false;
window.renderLessonWords=function(){const l=lessons[activeLesson];lessonContent.innerHTML=`<div class="v204stage">Leçon ${activeLesson+1}/${lessons.length}</div><h2 style="margin:4px 0">${l.title}</h2><div class="tiny">${l.words.length} éléments · chacun sera travaillé dans les deux sens</div><div style="margin-top:10px">${l.words.map(w=>`<div class="word"><div class="lux" style="font-size:21px">${w[0]}</div><div class="fr">${w[1]}</div><div class="audioLine"><button class="audioBtn">🔊 Écouter</button><span class="audioStatus"></span></div></div>`).join('')}</div><button class="primary" style="margin-top:12px" onclick="v204StartPractice()">Commencer la mémorisation</button>`};
window.v204StartPractice=function(){phaseCards=cardsForLesson();pos=0;good=0;renderPractice()};
function renderPractice(){if(pos>=phaseCards.length){lessonContent.innerHTML=`<div class="v204stage">Mémorisation terminée</div><h2>Tous les mots ont été vus dans les deux sens.</h2><button class="primary" onclick="v204StartTest()">Passer au test complet</button>`;return}const c=phaseCards[pos];shown=false;lessonContent.innerHTML=`<div class="v204stage">Mémorisation · ${c.dir}</div><div class="v204counter">${pos+1}/${phaseCards.length}</div><div class="v204prompt">${c.q}</div><button class="v204reveal" onclick="v204RevealPractice()">Révéler</button><div id="v204ans"></div>`}
window.v204RevealPractice=function(){if(shown)return;shown=true;const c=phaseCards[pos];document.getElementById('v204ans').innerHTML=`<div class="v204answer">${c.a}</div><div class="v204judge"><button class="bad" onclick="v204JudgePractice(false)">À revoir</button><button class="good" onclick="v204JudgePractice(true)">Je savais</button></div>`};
window.v204JudgePractice=function(ok){if(ok)good++;pos++;renderPractice()};
window.v204StartTest=function(){phaseCards=cardsForLesson();pos=0;good=0;renderTest()};
function renderTest(){if(pos>=phaseCards.length){const pct=Math.round(good/phaseCards.length*100);if(pct<80){lessonContent.innerHTML=`<div class="v204stage">Test vocabulaire</div><h2>${pct}%</h2><p class="muted">${good}/${phaseCards.length}. Il faut 80 %.</p><button class="primary" onclick="v204StartTest()">Refaire le test complet</button>`;return}startListening();return}const c=phaseCards[pos];shown=false;lessonContent.innerHTML=`<div class="v204stage">Test complet · ${c.dir}</div><div class="v204counter">${pos+1}/${phaseCards.length}</div><div class="v204prompt">${c.q}</div><button class="v204reveal" onclick="v204RevealTest()">Révéler</button><div id="v204ans"></div>`}
window.v204RevealTest=function(){if(shown)return;shown=true;const c=phaseCards[pos];document.getElementById('v204ans').innerHTML=`<div class="v204answer">${c.a}</div><div class="v204judge"><button class="bad" onclick="v204JudgeTest(false)">À revoir</button><button class="good" onclick="v204JudgeTest(true)">Je savais</button></div>`};
window.v204JudgeTest=function(ok){if(ok)good++;pos++;renderTest()};

let listenSet=[],listenPos=0,player=null;
function startListening(){listenSet=audioSet(activeLesson);listenPos=0;renderListening204()}
function renderListening204(){if(listenPos>=listenSet.length){renderSpeaking204();return}const x=listenSet[listenPos];lessonContent.innerHTML=`<div class="v204stage">Compréhension orale · ${listenPos+1}/${listenSet.length}</div><h2 style="margin:4px 0 10px">Écoute sans lire</h2><button class="primary" onclick="v204Play(this)">▶ Écouter</button><div class="v204prompt" style="font-size:19px">${x.q}</div>${x.o.map((o,i)=>`<button class="v204choice" onclick="v204AnswerAudio(${i},this)">${o}</button>`).join('')}<div id="v204audioReveal"></div>`}
window.v204Play=function(btn){const x=listenSet[listenPos];if(x.speech&&typeof window.v213Speak==='function'){window.v213Speak(x.speech,btn);return}try{player?.pause();player=new Audio(x.u);btn.textContent='🔊 Lecture…';player.play().then(()=>player.onended=()=>btn.textContent='▶ Réécouter').catch(()=>btn.textContent='Réessayer')}catch(e){btn.textContent='Réessayer'}};
window.v204AnswerAudio=function(choice,btn){const x=listenSet[listenPos],bs=btn.parentElement.querySelectorAll('.v204choice');bs.forEach((b,i)=>{b.disabled=true;if(i===x.a)b.classList.add('good')});if(choice!==x.a)btn.classList.add('bad');const r=document.getElementById('v204audioReveal');r.innerHTML=`<div class="v204feedback ${choice===x.a?'ok':'ko'}">${choice===x.a?'✓ Bonne réponse':'✗ Réponse attendue : '+x.o[x.a]}</div><div class="v204trans"><button onclick="v204Toggle(this,'lu')">Afficher le luxembourgeois</button><div class="box" data-lang="lu">${x.lu}</div><button onclick="v204Toggle(this,'fr')">Afficher le français</button><div class="box" data-lang="fr">${x.fr}</div></div><button class="primary" style="margin-top:10px" onclick="v204NextAudio()">${listenPos+1<listenSet.length?'Écoute suivante':'Passer à l’expression orale'}</button>`;r.scrollIntoView({behavior:'smooth',block:'nearest'})};
window.v204Toggle=function(btn,lang){const box=btn.parentElement.querySelector(`[data-lang="${lang}"]`),open=box.style.display==='block';box.style.display=open?'none':'block';btn.textContent=(open?'Afficher ':'Masquer ')+(lang==='lu'?'le luxembourgeois':'le français')};
window.v204NextAudio=function(){listenPos++;renderListening204()};

function plan(i){const l=lessons[i],w=l.words.map(x=>x[0]);if(i===0)return{task:'Fais ce mini-dialogue.',lines:[['Dis bonjour.','Moien!'],['Demande comment ça va.','Wéi geet et?'],['Prends congé.','Äddi!']]};if(i===3)return{task:'Présente-toi en 4 phrases.',lines:[['Je m’appelle…','Ech heeschen…'],['Je viens de…','Ech kommen aus…'],['J’habite à…','Ech wunnen zu…'],['Ajoute une information personnelle.','…']]};if(i===27)return{task:'Décris une image en 4 étapes.',lines:[['Dis ce que tu vois.','Op dem Bild gesinn ech…'],['Décris une personne/objet.','Ech gesinn…'],['Dis ce qui se passe.','Hien/Si…'],['Situe un élément.','virun / hannert / nieft…']]};return{task:`Parle de « ${l.title} » en 3 phrases.`,lines:[['Phrase 1 : information principale.',w[0]||'…'],['Phrase 2 : ajoute un détail.',w[1]||'…'],['Phrase 3 : ajoute quelque chose de personnel.',w[2]||'…']]}}
function renderSpeaking204(){const p=plan(activeLesson);lessonContent.innerHTML=`<div class="v204stage">Expression orale</div><div class="v204task">${p.task}</div>${p.lines.map((r,n)=>`<div class="v204line"><b>${n+1}. ${r[0]}</b><div class="lu">${r[1]}</div></div>`).join('')}<p class="muted">Lis les repères une fois, puis réponds sans les regarder.</p><button class="primary" onclick="v204SelfEval()">J’ai fini de parler</button><div id="v204eval"></div>`}
window.v204SelfEval=function(){document.getElementById('v204eval').innerHTML=`<div class="v204self"><button onclick="v204Rate(0)">Je n’y arrive pas</button><button onclick="v204Rate(1)">Avec beaucoup d’aide</button><button onclick="v204Rate(2)">Quelques hésitations</button><button onclick="v204Rate(3)">Sans aide</button></div>`};
window.v204Rate=function(n){if(n<2){document.getElementById('v204eval').innerHTML=`<div class="v204feedback ko">À retravailler : refais exactement la même réponse.</div><button class="primary" onclick="v204RetrySpeak()">Refaire maintenant</button>`;return}if(!state.done.includes(activeLesson)){state.done.push(activeLesson);state.done.sort((a,b)=>a-b);save()}lessonContent.innerHTML=`<div style="text-align:center;padding:20px 0"><div style="font-size:42px">✓</div><h2>Leçon validée</h2><p class="muted">Vocabulaire + compréhension + expression orale.</p><button class="primary" onclick="show('home')">Continuer</button></div>`};
window.v204RetrySpeak=renderSpeaking204;

// ----- Tuteur vocal -----
let tutor=document.getElementById('tutor');if(!tutor){tutor=document.createElement('section');tutor.id='tutor';tutor.className='screen';tutor.innerHTML='<button class="back" onclick="show(\'home\')">← Retour</button><div id="tutorContent"></div>';document.querySelector('.app').appendChild(tutor)}
let exam=document.getElementById('examPrep');if(!exam){exam=document.createElement('section');exam.id='examPrep';exam.className='screen';exam.innerHTML='<button class="back" onclick="show(\'home\')">← Retour</button><div id="examContent"></div>';document.querySelector('.app').appendChild(exam)}
const tutorDialogs=[
 [{fr:'Dis bonjour.',need:['moien'],hint:'Moien!'}, {fr:'Demande comment ça va.',need:['wei','geet'],hint:'Wéi geet et?'}, {fr:'Dis au revoir.',need:['addi'],hint:'Äddi!'}],
 [{fr:'Dis ton prénom.',need:['heeschen'],hint:'Ech heeschen …'}, {fr:'Dis où tu habites.',need:['wunnen'],hint:'Ech wunnen zu …'}, {fr:'Dis d’où tu viens.',need:['kommen','aus'],hint:'Ech kommen aus …'}]
];
let tutorSet=[],tutorPos=0;
function norm(s){return (s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9 ]/g,' ')}
window.openTutor=function(){const idx=(state.done||[]).length>=3?1:0;tutorSet=tutorDialogs[idx];tutorPos=0;renderTutor();show('tutor')};
function renderTutor(){const x=tutorSet[tutorPos];if(!x){document.getElementById('tutorContent').innerHTML=`<div class="v204stage">Tuteur vocal</div><h2>Dialogue terminé</h2><button class="primary" onclick="openTutor()">Refaire un dialogue</button>`;return}document.getElementById('tutorContent').innerHTML=`<div class="v204stage">Tuteur vocal · ${tutorPos+1}/${tutorSet.length}</div><div class="v204bubble"><b>Le tuteur :</b><br>${x.fr}</div><button class="v204mic" onclick="v204ListenSpeech()">🎙 Répondre à voix haute</button><button class="v204reveal" style="margin-top:9px" onclick="v204ShowHint()">Voir un repère</button><div id="v204speech"></div>`}
window.v204ShowHint=function(){document.getElementById('v204speech').innerHTML=`<div class="v204heard">Repère : <b>${tutorSet[tutorPos].hint}</b></div>`};
window.v204ListenSpeech=function(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){document.getElementById('v204speech').innerHTML=`<div class="v204feedback ko">La reconnaissance vocale du navigateur n’est pas disponible ici.</div><div class="v204heard">Dis la réponse à voix haute, puis compare avec : <b>${tutorSet[tutorPos].hint}</b></div><button class="primary" onclick="v204TutorNext()">J’ai répondu</button>`;return}const r=new SR();r.lang='lb-LU';r.interimResults=false;r.maxAlternatives=1;document.getElementById('v204speech').innerHTML='<div class="v204heard">🎙 J’écoute…</div>';r.onresult=e=>{const txt=e.results[0][0].transcript,n=norm(txt),x=tutorSet[tutorPos],score=x.need.filter(k=>n.includes(norm(k))).length;document.getElementById('v204speech').innerHTML=`<div class="v204heard"><b>J’ai entendu :</b><br>${txt}</div><div class="v204feedback ${score===x.need.length?'ok':'ko'}">${score===x.need.length?'✓ Les éléments attendus sont présents.':'Il manque un élément important. Repère : '+x.hint}</div><button class="primary" onclick="v204TutorNext()">Continuer</button>`};r.onerror=e=>{document.getElementById('v204speech').innerHTML=`<div class="v204feedback ko">Reconnaissance vocale indisponible (${e.error}).</div><div class="v204heard">Repère : <b>${tutorSet[tutorPos].hint}</b></div><button class="primary" onclick="v204TutorNext()">Continuer</button>`};try{r.start()}catch(e){r.onerror({error:'démarrage'})}};
window.v204TutorNext=function(){tutorPos++;renderTutor()};

window.openExamPrep=function(){document.getElementById('examContent').innerHTML=`<div class="v204stage">Préparation Sproochentest</div><h2 style="margin:4px 0 12px">Entraînement ciblé examen</h2><div class="v204examRow"><b>Entretien A2</b><small>Questions personnelles courtes avec réponses guidées à voix haute.</small><button onclick="openTutor()">Commencer l’entretien</button></div><div class="v204examRow"><b>Description d’image</b><small>Réponse structurée : vue générale → personnes/objets → actions → positions.</small><button onclick="v204StartImageDrill()">S’entraîner</button></div><div class="v204examRow"><b>Compréhension orale</b><small>Écoutes avec QCM, transcription luxembourgeoise et française après réponse.</small><button onclick="v204StartFreeListening()">S’entraîner</button></div>`;show('examPrep')};
window.v204StartImageDrill=function(){activeLesson=Math.min(27,lessons.length-1);renderSpeaking204();show('lesson')};
window.v204StartFreeListening=function(){activeLesson=Math.min((state.done||[]).length,lessons.length-1);startListening();show('lesson')};

const oldHome=window.renderHome;window.renderHome=function(){oldHome();let box=document.getElementById('v204modes');if(!box){box=document.createElement('div');box.id='v204modes';const hero=document.querySelector('#home .hero');hero?.insertAdjacentElement('afterend',box)}if(box)box.innerHTML=`<div class="v204modes"><button onclick="show('review')"><span>↻</span>Révisions</button><button onclick="openTutor()"><span>🎙</span>Tuteur vocal</button><button onclick="openExamPrep()"><span>◎</span>Prépa examen</button></div>`;document.querySelectorAll('.brand small').forEach(x=>x.textContent='V20.4 · parcours + oral + examen')};

document.title='Sproochentest Lëtzebuergesch V20.4';renderHome();
})();
